-- This code was generated by Codex.

import LeanNct.Introduction
import LeanNct.RealToErgodic
import LeanNct.WienerSpace
import LeanNct.Preliminaries.Notation
import LeanNct.Preliminaries.MultiplicativelySpacedMonotoneSequences
import LeanNct.Preliminaries.Gaussians
import LeanNct.Preliminaries.KKernels
import LeanNct.Preliminaries.MKernels
import LeanNct.Preliminaries.BumpsAndEstimates
import LeanNct.Preliminaries.ConvolutionAlongVector
import LeanNct.MainArgument.SandwichKernel
import LeanNct.MainArgument.MultipliersHLN
import LeanNct.MainArgument.GaussianDomination
import LeanNct.MainArgument.MainInduction
import LeanNct.Reduction.AToLambda
import LeanNct.Reduction.VariationSeminorms
import LeanNct.Reduction.BumpFunctions
import LeanNct.Reduction.WindowsAndPairs
import LeanNct.Reduction.SmoothingDecomposition
import LeanNct.Reduction.Miscellany
import LeanNct.Reduction.OnDiagonalMainArgument
import LeanNct.Reduction.OnDiagonalOffDiagonal
import LeanNct.Reduction.TwistedAverages
import LeanNct.Reduction.FinalReduction

#check Codex.Introduction.mainTwistedTheorem

#print axioms Codex.Introduction.mainTwistedTheorem
