/- This code was generated by Codex. -/

module
public import LeanNct.Auto.Preliminaries.BumpsAndEstimates

@[expose] public section
set_option linter.style.header false

/-!
# Bump functions

Formalization of the ``Bump functions'' subsection of the reduction argument.
-/

namespace Auto

open MeasureTheory Set
open scoped BigOperators FourierTransform Real RealInnerProductSpace



noncomputable section
/--
The multiplication operator $X\phi(u)=u\phi(u)$ from
(`auto:multiplication-operator-X`).
-/
noncomputable def multiplicationOperatorX {E : Type*} [NormedAddCommGroup E]
    [NormedSpace ℝ E] (phi : ℝ → E) : ℝ → E :=
  fun u ↦ u • phi u

/--
The logarithmic-derivative operator $T\phi=(X\phi)'$ used in
Lemma `Auto.fourierDerivativeMul`.
-/
noncomputable def aux_T {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (phi : ℝ → E) : ℝ → E :=
  fun x ↦ deriv (multiplicationOperatorX phi) x

/--
**Lemma.**

For a Schwartz function $\phi:\mathbb{R}\to\mathbb{C}$ let
$T\phi(x)=\frac{d}{dx} (x \phi(x))|_x$. Then
for every $m\ge 0$,

$$
(\widehat{T\phi})^{(m)}(\xi) = -(m (\widehat{\phi})^{(m)}(\xi) + \xi (\widehat{\phi})^{(m+1)}(\xi)).
$$
-/
theorem fourierDerivativeMul (phi : SchwartzMap ℝ ℂ) (m : ℕ) (xi : ℝ) :
    iteratedDeriv m
        (FourierTransform.fourier (aux_T (fun x : ℝ ↦ phi x))) xi =
      -((m : ℂ) * iteratedDeriv m
          (FourierTransform.fourier (fun x : ℝ ↦ phi x)) xi +
        (xi : ℂ) * iteratedDeriv (m + 1)
        (FourierTransform.fourier (fun x : ℝ ↦ phi x)) xi) := by
  let psi : SchwartzMap ℝ ℂ :=
    SchwartzMap.smulLeftCLM ℂ (fun x : ℝ ↦ (x : ℂ)) phi
  let tau : SchwartzMap ℝ ℂ := SchwartzMap.derivCLM ℂ ℂ psi
  have hpsi : ∀ x : ℝ, psi x = multiplicationOperatorX (fun x : ℝ ↦ phi x) x := by
    intro x
    change (SchwartzMap.smulLeftCLM ℂ (fun x : ℝ ↦ (x : ℂ)) phi) x = _
    rw [SchwartzMap.smulLeftCLM_apply_apply (by fun_prop)]
    simp [multiplicationOperatorX]
  have hpsi_fun : (psi : ℝ → ℂ) = multiplicationOperatorX (fun x : ℝ ↦ phi x) :=
    funext hpsi
  have htau : ∀ x : ℝ, tau x = aux_T (fun x : ℝ ↦ phi x) x := by
    intro x
    simp only [tau, aux_T, SchwartzMap.derivCLM_apply]
    rw [hpsi_fun]
  have hlineTau : LineDeriv.lineDerivOp (1 : ℝ) psi = tau := by
    ext x
    simp only [SchwartzMap.lineDerivOp_apply_eq_fderiv, tau, SchwartzMap.derivCLM_apply]
    rw [fderiv_apply_one_eq_deriv]
  have hsmul : SchwartzMap.smulLeftCLM ℂ (fun x : ℝ ↦ ⟪x, (1 : ℝ)⟫) phi = psi := by
    ext x
    rw [SchwartzMap.smulLeftCLM_apply_apply (by fun_prop)]
    calc
      ⟪x, (1 : ℝ)⟫ • phi x = (x : ℂ) * phi x := by
        simp
      _ = psi x := by
        rw [SchwartzMap.smulLeftCLM_apply_apply (by fun_prop)]
        simp only [smul_eq_mul]
  have hDerivPhi :
      SchwartzMap.derivCLM ℂ ℂ (FourierTransform.fourier phi) =
        FourierTransform.fourier (-(2 * Real.pi * Complex.I) • psi) := by
    calc
      SchwartzMap.derivCLM ℂ ℂ (FourierTransform.fourier phi) =
          LineDeriv.lineDerivOp (1 : ℝ) (FourierTransform.fourier phi) := by
        ext x
        simp only [SchwartzMap.derivCLM_apply, SchwartzMap.lineDerivOp_apply_eq_fderiv]
        rw [fderiv_apply_one_eq_deriv]
      _ = FourierTransform.fourier
          (-(2 * Real.pi * Complex.I) •
            SchwartzMap.smulLeftCLM ℂ (fun x : ℝ ↦ ⟪x, (1 : ℝ)⟫) phi) :=
          SchwartzMap.lineDerivOp_fourier_eq phi (1 : ℝ)
      _ = FourierTransform.fourier (-(2 * Real.pi * Complex.I) • psi) := by rw [hsmul]
  have hFourierTau :
      FourierTransform.fourier tau =
        (2 * Real.pi * Complex.I) •
          SchwartzMap.smulLeftCLM ℂ (fun x : ℝ ↦ ⟪x, (1 : ℝ)⟫)
            (FourierTransform.fourier psi) := by
    rw [← hlineTau]
    exact SchwartzMap.fourier_lineDerivOp_eq psi (1 : ℝ)
  have hDerivPhiAt (x : ℝ) :
      deriv (FourierTransform.fourier (phi : ℝ → ℂ)) x =
        -(2 * Real.pi * Complex.I) *
          FourierTransform.fourier (psi : ℝ → ℂ) x := by
    have h := congrArg (fun f : SchwartzMap ℝ ℂ ↦ f x) hDerivPhi
    simpa [SchwartzMap.fourier_coe, smul_eq_mul, mul_assoc] using h
  have hFourierTauAt (x : ℝ) :
      FourierTransform.fourier (tau : ℝ → ℂ) x =
        (2 * Real.pi * Complex.I) * (x : ℂ) *
          FourierTransform.fourier (psi : ℝ → ℂ) x := by
    have h := congrArg (fun f : SchwartzMap ℝ ℂ ↦ f x) hFourierTau
    change FourierTransform.fourier (tau : ℝ → ℂ) x =
      (2 * Real.pi * Complex.I) *
        (SchwartzMap.smulLeftCLM ℂ (fun y : ℝ ↦ ⟪y, (1 : ℝ)⟫)
          (FourierTransform.fourier psi)) x at h
    rw [SchwartzMap.smulLeftCLM_apply_apply (by fun_prop)] at h
    simpa [SchwartzMap.fourier_coe, smul_eq_mul, mul_assoc] using h
  have htau_fun : (tau : ℝ → ℂ) = aux_T (fun x : ℝ ↦ phi x) := funext htau
  have hbase : FourierTransform.fourier (aux_T (fun x : ℝ ↦ phi x)) =
      fun x : ℝ ↦ -(x : ℂ) *
        deriv (FourierTransform.fourier (phi : ℝ → ℂ)) x := by
    ext x
    rw [← htau_fun, hFourierTauAt, hDerivPhiAt]
    ring
  have hdiff (k : ℕ) :
      Differentiable ℝ (iteratedDeriv k (FourierTransform.fourier (phi : ℝ → ℂ))) := by
    apply ContDiff.differentiable_iteratedDeriv' k
    simpa [SchwartzMap.fourier_coe] using
      (FourierTransform.fourier phi : SchwartzMap ℝ ℂ).smooth (k + 1)
  rw [hbase]
  have hformula : ∀ k : ℕ,
      iteratedDeriv k (fun x : ℝ ↦ -(x •
          deriv (FourierTransform.fourier (phi : ℝ → ℂ)) x)) =
        fun x : ℝ ↦ -((k : ℝ) •
          iteratedDeriv k (FourierTransform.fourier (phi : ℝ → ℂ)) x +
          x • iteratedDeriv (k + 1)
            (FourierTransform.fourier (phi : ℝ → ℂ)) x) := by
    intro k
    induction k with
    | zero =>
        funext x
        simp only [iteratedDeriv_zero, Nat.cast_zero, zero_add]
        rw [iteratedDeriv_one]
        simp
    | succ k ih =>
        rw [iteratedDeriv_succ, ih]
        funext x
        have hiter (j : ℕ) : HasDerivAt
            (iteratedDeriv j (FourierTransform.fourier (phi : ℝ → ℂ)))
            (iteratedDeriv (j + 1) (FourierTransform.fourier (phi : ℝ → ℂ)) x) x := by
          simpa only [iteratedDeriv_succ] using (hdiff j x).hasDerivAt
        have hid : HasDerivAt (fun y : ℝ ↦ y) 1 x := hasDerivAt_id' x
        have hA : HasDerivAt (fun y : ℝ ↦ (k : ℝ) •
            iteratedDeriv k (FourierTransform.fourier (phi : ℝ → ℂ)) y)
            ((k : ℝ) • iteratedDeriv (k + 1)
              (FourierTransform.fourier (phi : ℝ → ℂ)) x) x :=
          (hiter k).const_smul (k : ℝ)
        have hBraw : HasDerivAt
            ((fun y : ℝ ↦ y) •
              iteratedDeriv (k + 1) (FourierTransform.fourier (phi : ℝ → ℂ)))
            (x • iteratedDeriv (k + 1 + 1)
              (FourierTransform.fourier (phi : ℝ → ℂ)) x +
              (1 : ℝ) • iteratedDeriv (k + 1)
                (FourierTransform.fourier (phi : ℝ → ℂ)) x) x := by
          exact HasDerivAt.smul (𝕜' := ℝ) hid (hiter (k + 1))
        have hBfun : ((fun y : ℝ ↦ y) •
            iteratedDeriv (k + 1) (FourierTransform.fourier (phi : ℝ → ℂ))) =
            fun y : ℝ ↦ y •
              iteratedDeriv (k + 1) (FourierTransform.fourier (phi : ℝ → ℂ)) y := by
          rfl
        have hB : HasDerivAt (fun y : ℝ ↦ y •
            iteratedDeriv (k + 1) (FourierTransform.fourier (phi : ℝ → ℂ)) y)
            (x • iteratedDeriv (k + 1 + 1)
              (FourierTransform.fourier (phi : ℝ → ℂ)) x +
              (1 : ℝ) • iteratedDeriv (k + 1)
                (FourierTransform.fourier (phi : ℝ → ℂ)) x) x := by
          rw [← hBfun]
          exact hBraw
        have hsum : HasDerivAt (fun y : ℝ ↦ -((k : ℝ) •
            iteratedDeriv k (FourierTransform.fourier (phi : ℝ → ℂ)) y +
            y • iteratedDeriv (k + 1)
              (FourierTransform.fourier (phi : ℝ → ℂ)) y))
            (-((k : ℝ) • iteratedDeriv (k + 1)
              (FourierTransform.fourier (phi : ℝ → ℂ)) x +
              (x • iteratedDeriv (k + 1 + 1)
                (FourierTransform.fourier (phi : ℝ → ℂ)) x +
              (1 : ℝ) • iteratedDeriv (k + 1)
                (FourierTransform.fourier (phi : ℝ → ℂ)) x))) x := by
          exact (hA.add hB).neg
        rw [hsum.deriv]
        simp [Nat.cast_add]
        ring
  simpa [smul_eq_mul] using congrFun (hformula m) xi

/-- The explicit constant in Lemma `Auto.wideBump`. -/
noncomputable def C_wideBump (N : ℝ) : ℝ :=
  Real.rpow 2 (3 * N)

/--
**Lemma.**

Let $k \leq 2$, $t\in [2^{1-k}, 2^{2-k}]$. Then for every $u\in \mathbb{R}$ and $N\ge 0$,

$$
\langle u-t\rangle^{N} \le C_{\text{lem:widebump},N} 2^{-kN}\langle u\rangle^{N},
$$

where $C_{\text{lem:widebump},N}=2^{3N}$.

See also `Auto.wideBump`.
-/
theorem wideBump (k : ℤ) (hk : k ≤ 2) (t : ℝ)
    (ht : t ∈ Set.Icc ((2 : ℝ) ^ (1 - k)) ((2 : ℝ) ^ (2 - k)))
    (u N : ℝ) (hN : 0 ≤ N) :
    Real.rpow (bracketBump (u - t)) N ≤
      C_wideBump N * Real.rpow 2 (-((k : ℝ) * N)) *
        Real.rpow (bracketBump u) N := by
  have htpos : 0 < t := (zpow_pos (by norm_num : (0 : ℝ) < 2) _).trans_le ht.1
  have hpowone : 1 ≤ (2 : ℝ) ^ (2 - k) := by
    apply one_le_zpow₀
    · norm_num
    · omega
  have hfactor : 1 + t ≤ (2 : ℝ) ^ (3 - k) := by
    calc
      1 + t ≤ 1 + (2 : ℝ) ^ (2 - k) := by gcongr; exact ht.2
      _ ≤ (2 : ℝ) ^ (2 - k) + (2 : ℝ) ^ (2 - k) := by linarith
      _ = (2 : ℝ) ^ (3 - k) := by
        rw [show (3 - k : ℤ) = (2 - k) + 1 by omega,
          zpow_add₀ (by norm_num : (2 : ℝ) ≠ 0), zpow_one]
        ring
  have htri : 1 + |u| ≤ (1 + |u - t|) * (1 + t) := by
    calc
      1 + |u| = 1 + |(u - t) + t| := by congr 2; ring
      _ ≤ 1 + (|u - t| + |t|) := by gcongr; exact abs_add_le _ _
      _ ≤ (1 + |u - t|) * (1 + t) := by
        rw [abs_of_pos htpos]
        nlinarith [abs_nonneg (u - t)]
  have hdenleft : 0 < 1 + |u - t| := by positivity
  have hdenright : 0 < 1 + |u| := by positivity
  have hbase : bracketBump (u - t) ≤ (1 + t) * bracketBump u := by
    rw [bracketBump, bracketBump]
    rw [← div_eq_mul_inv, ← one_div]
    rw [div_le_div_iff₀ hdenleft hdenright]
    simpa [mul_comm] using htri
  have hbrpos (v : ℝ) : 0 < bracketBump v := by
    rw [bracketBump]
    exact inv_pos.mpr (by positivity)
  have hbase' : bracketBump (u - t) ≤ (2 : ℝ) ^ (3 - k) * bracketBump u :=
    hbase.trans (mul_le_mul_of_nonneg_right hfactor (hbrpos u).le)
  have hp : Real.rpow (bracketBump (u - t)) N ≤
      Real.rpow ((2 : ℝ) ^ (3 - k) * bracketBump u) N :=
    Real.rpow_le_rpow (hbrpos _).le hbase' hN
  have hp' : Real.rpow (bracketBump (u - t)) N ≤
      Real.rpow ((2 : ℝ) ^ (3 - k)) N * Real.rpow (bracketBump u) N :=
    hp.trans_eq (Real.mul_rpow (zpow_pos (by norm_num) _).le (hbrpos _).le)
  calc
    Real.rpow (bracketBump (u - t)) N ≤
        Real.rpow ((2 : ℝ) ^ (3 - k)) N * Real.rpow (bracketBump u) N := hp'
    _ = Real.rpow 2 ((3 - (k : ℝ)) * N) * Real.rpow (bracketBump u) N := by
      congr 1
      simpa using
        (Real.rpow_intCast_mul (x := (2 : ℝ)) (by norm_num : (0 : ℝ) ≤ 2) (3 - k) N).symm
    _ = C_wideBump N * Real.rpow 2 (-((k : ℝ) * N)) *
        Real.rpow (bracketBump u) N := by
      rw [C_wideBump]
      calc
        Real.rpow 2 ((3 - (k : ℝ)) * N) * Real.rpow (bracketBump u) N =
            Real.rpow 2 (3 * N + -((k : ℝ) * N)) * Real.rpow (bracketBump u) N := by
          congr 2
          ring
        _ = (Real.rpow 2 (3 * N) * Real.rpow 2 (-((k : ℝ) * N))) *
            Real.rpow (bracketBump u) N := by
          exact congrArg (fun q : ℝ ↦ q * Real.rpow (bracketBump u) N)
            (Real.rpow_add (x := (2 : ℝ)) (by norm_num : (0 : ℝ) < 2)
              (3 * N) (-((k : ℝ) * N)))

/-- The constant in Lemma `Auto.thetaTOffcenter`. -/
noncomputable def C_thetaTOffcenter : ℝ := 133

theorem thetaTOffcenter_bracket_pos (x : ℝ) : 0 < bracketBump x := by
  rw [bracketBump]
  positivity

theorem thetaTOffcenter_bracket_le_one (x : ℝ) : bracketBump x ≤ 1 := by
  rw [bracketBump]
  exact (inv_le_one₀ (by positivity)).2 (by linarith [abs_nonneg x])

theorem thetaTOffcenter_bracket_sq_le_three_halves (x : ℝ) :
    bracketBump x ^ 2 ≤ Real.rpow (bracketBump x) (3 / 2 : ℝ) := by
  rw [← Real.rpow_natCast]
  exact Real.rpow_le_rpow_of_exponent_ge
    (thetaTOffcenter_bracket_pos x) (thetaTOffcenter_bracket_le_one x) (by norm_num)

theorem thetaTOffcenter_sq_eq_scaled (x : ℝ) :
    bracketBump x ^ 2 = scaledBracketBumpReal 2 1 x := by
  unfold bracketBump scaledBracketBumpReal
  norm_num only [inv_one, one_mul]
  calc
    (1 + |x|)⁻¹ ^ 2 = ((1 + |x|) ^ 2)⁻¹ := inv_pow _ _
    _ = (Real.rpow (1 + |x|) (2 : ℝ))⁻¹ :=
      congrArg Inv.inv (Real.rpow_natCast (1 + |x|) 2).symm
    _ = Real.rpow (1 + |x|) (-(2 : ℝ)) :=
      (Real.rpow_neg (by positivity) _).symm

theorem thetaTOffcenter_mass (R v : ℝ) (hR : 0 < R) :
    ∫ t : ℝ in Set.Icc 1 2, bracketBump (v - t * R) ^ 2 ≤ 2 * R⁻¹ := by
  let g : ℝ → ℝ := fun t ↦ bracketBump (v - t * R) ^ 2
  let f : ℝ → ℝ := fun t ↦ R⁻¹ *
    scaledBracketBumpReal 2 R⁻¹ (v / R - t)
  have hf : Integrable f := by
    have hbase := aux_integrable_scaledBracketBumpReal_translate 2 R⁻¹ (v / R)
      (by norm_num : (1 : ℝ) < 2) (inv_pos.mpr hR)
    exact hbase.const_mul R⁻¹
  have hfg : f = g := by
    funext t
    dsimp [f, g]
    rw [thetaTOffcenter_sq_eq_scaled]
    unfold scaledBracketBumpReal
    norm_num only [inv_one, one_mul]
    have harg : (R⁻¹)⁻¹ * (v / R - t) = v - t * R := by
      field_simp [hR.ne']
    rw [harg]
    field_simp [hR.ne']
  have hg : Integrable g := by rw [← hfg]; exact hf
  have hnonneg (t : ℝ) : 0 ≤ g t := sq_nonneg _
  have hfull : ∫ t : ℝ, g t = 2 * R⁻¹ := by
    rw [← hfg, integral_const_mul]
    have hval := aux_integral_scaledBracketBumpReal_eq 2 R⁻¹ (v / R)
      (by norm_num : (1 : ℝ) < 2) (inv_pos.mpr hR)
    rw [hval]
    ring
  change ∫ t : ℝ in Set.Icc 1 2, g t ≤ _
  rw [← hfull]
  exact MeasureTheory.setIntegral_le_integral hg (ae_of_all _ hnonneg)

theorem thetaTOffcenter_integrable_shift (R v : ℝ) (hR : 0 < R) :
    Integrable (fun t : ℝ ↦ bracketBump (v - t * R) ^ 2) := by
  let f : ℝ → ℝ := fun t ↦ R⁻¹ *
    scaledBracketBumpReal 2 R⁻¹ (v / R - t)
  have hf : Integrable f := by
    have hbase := aux_integrable_scaledBracketBumpReal_translate 2 R⁻¹ (v / R)
      (by norm_num : (1 : ℝ) < 2) (inv_pos.mpr hR)
    exact hbase.const_mul R⁻¹
  have hfg : f = fun t : ℝ ↦ bracketBump (v - t * R) ^ 2 := by
    funext t
    dsimp [f]
    rw [thetaTOffcenter_sq_eq_scaled]
    unfold scaledBracketBumpReal
    norm_num only [inv_one, one_mul]
    have harg : (R⁻¹)⁻¹ * (v / R - t) = v - t * R := by
      field_simp [hR.ne']
    rw [harg]
    field_simp [hR.ne']
  rw [← hfg]
  exact hf

theorem thetaTOffcenter_scale (R c v : ℝ) (hR : 0 < R) (hc : 0 < c)
    (h : 1 + |v| ≤ c * R) :
    Real.rpow R (-(3 / 2 : ℝ)) ≤
      Real.rpow c (3 / 2 : ℝ) * Real.rpow (bracketBump v) (3 / 2 : ℝ) := by
  have hbase : R⁻¹ ≤ c * bracketBump v := by
    change R⁻¹ ≤ c / (1 + |v|)
    rw [le_div_iff₀ (by positivity)]
    calc
      R⁻¹ * (1 + |v|) ≤ R⁻¹ * (c * R) :=
        mul_le_mul_of_nonneg_left h (inv_nonneg.mpr hR.le)
      _ = c := by field_simp [hR.ne']
  calc
    Real.rpow R (-(3 / 2 : ℝ)) = Real.rpow R⁻¹ (3 / 2 : ℝ) :=
      Real.rpow_neg_eq_inv_rpow R _
    _ ≤ Real.rpow (c * bracketBump v) (3 / 2 : ℝ) :=
      Real.rpow_le_rpow (inv_nonneg.mpr hR.le) hbase (by norm_num)
    _ = Real.rpow c (3 / 2 : ℝ) * Real.rpow (bracketBump v) (3 / 2 : ℝ) :=
      Real.mul_rpow hc.le (thetaTOffcenter_bracket_pos v).le

theorem thetaTOffcenter_large (R v t : ℝ) (hR : 0 < R) (hv : 3 * R ≤ |v|)
    (ht : t ∈ Set.Icc 1 2) :
    bracketBump (v - t * R) ≤ 3 * bracketBump v := by
  have ht0 : 0 ≤ t := by linarith [ht.1]
  have htR : |t * R| ≤ 2 * R := by
    rw [abs_of_nonneg (mul_nonneg ht0 hR.le)]
    gcongr
    exact ht.2
  have habs : |v| ≤ |v - t * R| + |t * R| := by
    calc
      |v| = |(v - t * R) + t * R| := by congr 1; ring
      _ ≤ |v - t * R| + |t * R| := abs_add_le _ _
  have hshift : |v| ≤ 3 * |v - t * R| := by
    nlinarith
  have htri : 1 + |v| ≤ 3 * (1 + |v - t * R|) := by
    nlinarith [abs_nonneg (v - t * R)]
  rw [bracketBump, bracketBump]
  calc
    (1 + |v - t * R|)⁻¹ = 1 / (1 + |v - t * R|) := by rw [one_div]
    _ ≤ 3 / (1 + |v|) :=
      (div_le_div_iff₀ (by positivity) (by positivity)).2 (by simpa using htri)
    _ = 3 * (1 + |v|)⁻¹ := by rw [div_eq_mul_inv]

theorem thetaTOffcenter_lead (k : ℤ) :
    Real.rpow 2 ((k : ℝ) / 2) =
      Real.rpow ((2 : ℝ) ^ (-k)) (-(1 / 2 : ℝ)) := by
  calc
    Real.rpow 2 ((k : ℝ) / 2) =
        Real.rpow 2 ((((-k : ℤ) : ℝ) * (-(1 / 2 : ℝ)))) := by
      congr 1
      push_cast
      ring
    _ = Real.rpow ((2 : ℝ) ^ (-k)) (-(1 / 2 : ℝ)) := by
      simpa using (Real.rpow_intCast_mul (x := (2 : ℝ)) (by norm_num : (0 : ℝ) ≤ 2)
        (-k) (-(1 / 2 : ℝ)))

theorem thetaTOffcenter_combine (R : ℝ) (hR : 0 < R) :
    Real.rpow R (-(1 / 2 : ℝ)) * R⁻¹ = Real.rpow R (-(3 / 2 : ℝ)) := by
  calc
    Real.rpow R (-(1 / 2 : ℝ)) * R⁻¹ =
        Real.rpow R (-(1 / 2 : ℝ)) * Real.rpow R (-1 : ℝ) := by
          rw [show R⁻¹ = Real.rpow R (-1 : ℝ) from (Real.rpow_neg_one R).symm]
    _ = Real.rpow R (-(1 / 2 : ℝ) + (-1 : ℝ)) :=
      (Real.rpow_add hR _ _).symm
    _ = Real.rpow R (-(3 / 2 : ℝ)) := by congr 1; ring

theorem thetaTOffcenter_rpow_three : Real.rpow 3 (3 / 2 : ℝ) ≤ 6 := by
  have hsqrt : Real.sqrt 3 ≤ 2 := by
    nlinarith [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 3), Real.sqrt_nonneg (3 : ℝ)]
  calc
    Real.rpow 3 (3 / 2 : ℝ) = Real.rpow 3 (1 / 2 : ℝ) * 3 := by
      convert Real.rpow_add (by norm_num : (0 : ℝ) < 3) (1 / 2 : ℝ) 1 using 1 <;> norm_num
    _ = Real.sqrt 3 * 3 := congrArg (fun z : ℝ ↦ z * 3) (Real.sqrt_eq_rpow 3).symm
    _ ≤ 2 * 3 := by gcongr
    _ = 6 := by norm_num

theorem thetaTOffcenter_rpow_seven_halves :
    Real.rpow (7 / 2 : ℝ) (3 / 2 : ℝ) ≤ 7 := by
  have hsqrt : Real.sqrt (7 / 2 : ℝ) ≤ 2 := by
    nlinarith [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 7 / 2),
      Real.sqrt_nonneg (7 / 2 : ℝ)]
  calc
    Real.rpow (7 / 2 : ℝ) (3 / 2 : ℝ) =
        Real.rpow (7 / 2 : ℝ) (1 / 2 : ℝ) * (7 / 2 : ℝ) := by
      convert Real.rpow_add (by norm_num : (0 : ℝ) < 7 / 2) (1 / 2 : ℝ) 1 using 1 <;> norm_num
    _ = Real.sqrt (7 / 2 : ℝ) * (7 / 2 : ℝ) :=
      congrArg (fun z : ℝ ↦ z * (7 / 2 : ℝ)) (Real.sqrt_eq_rpow (7 / 2 : ℝ)).symm
    _ ≤ 2 * (7 / 2 : ℝ) := by gcongr
    _ = 7 := by norm_num

theorem thetaTOffcenter_rpow_thirteen_halves :
    Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) ≤ 133 / 8 := by
  have hsqrt : Real.sqrt (13 / 2 : ℝ) ≤ 133 / 52 := by
    nlinarith [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 13 / 2),
      Real.sqrt_nonneg (13 / 2 : ℝ)]
  calc
    Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) =
        Real.rpow (13 / 2 : ℝ) (1 / 2 : ℝ) * (13 / 2 : ℝ) := by
      convert Real.rpow_add (by norm_num : (0 : ℝ) < 13 / 2) (1 / 2 : ℝ) 1 using 1 <;> norm_num
    _ = Real.sqrt (13 / 2 : ℝ) * (13 / 2 : ℝ) :=
      congrArg (fun z : ℝ ↦ z * (13 / 2 : ℝ)) (Real.sqrt_eq_rpow (13 / 2 : ℝ)).symm
    _ ≤ (133 / 52 : ℝ) * (13 / 2 : ℝ) := by gcongr
    _ = 133 / 8 := by norm_num

theorem thetaTOffcenter_scaled_neg (x : ℝ) :
    scaledBracketBumpReal 2 1 (-x) = scaledBracketBumpReal 2 1 x := by
  unfold scaledBracketBumpReal
  norm_num only [inv_one, one_mul]
  rw [abs_neg]

theorem thetaTOffcenter_two_point (a b : ℝ) :
    bracketBump a ^ 2 * bracketBump b ^ 2 ≤
      2 * bracketBump (a - b) ^ 2 * (bracketBump a ^ 2 + bracketBump b ^ 2) := by
  rw [thetaTOffcenter_sq_eq_scaled, thetaTOffcenter_sq_eq_scaled, thetaTOffcenter_sq_eq_scaled]
  rw [← thetaTOffcenter_scaled_neg b]
  calc
    scaledBracketBumpReal 2 1 a * scaledBracketBumpReal 2 1 (-b) ≤
        Real.rpow 2 ((2 : ℝ) - 1) * scaledBracketBumpReal 2 1 (a - b) *
          (scaledBracketBumpReal 2 1 a + scaledBracketBumpReal 2 1 (-b)) :=
      aux_twoBump_pointwise_sameExponent 2 1 1 a (-b)
        (by norm_num : (1 : ℝ) < 2) (by norm_num : (0 : ℝ) < 1)
        (by norm_num : (0 : ℝ) < 1) le_rfl
    _ = 2 * scaledBracketBumpReal 2 1 (a - b) *
          (scaledBracketBumpReal 2 1 a + scaledBracketBumpReal 2 1 (-b)) := by
      norm_num [Real.rpow_one]

theorem thetaTOffcenter_one_small (R v w : ℝ) (hR : 0 < R) (hRtwo : 2 ≤ R)
    (hv : ¬ 3 * R ≤ |v|) (hw : 3 * R ≤ |w|) :
    Real.rpow R (-(1 / 2 : ℝ)) *
        ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
      126 * (Real.rpow (bracketBump v) (3 / 2 : ℝ) *
        Real.rpow (bracketBump w) (3 / 2 : ℝ)) := by
  have hvsmall : |v| < 3 * R := lt_of_not_ge hv
  have hscale : Real.rpow R (-(3 / 2 : ℝ)) ≤
      Real.rpow (7 / 2 : ℝ) (3 / 2 : ℝ) *
        Real.rpow (bracketBump v) (3 / 2 : ℝ) := by
    apply thetaTOffcenter_scale R (7 / 2 : ℝ) v hR (by norm_num)
    nlinarith
  have hpoint (t : ℝ) (ht : t ∈ Set.Icc 1 2) :
      bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
        (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
          bracketBump (v - t * R) ^ 2 := by
    have hlarge := thetaTOffcenter_large R w t hR hw ht
    have hp : bracketBump (w - t * R) ^ 2 ≤
        9 * Real.rpow (bracketBump w) (3 / 2 : ℝ) := by
      calc
        bracketBump (w - t * R) ^ 2 ≤ (3 * bracketBump w) ^ 2 :=
          pow_le_pow_left₀ (thetaTOffcenter_bracket_pos _).le hlarge 2
        _ = 9 * bracketBump w ^ 2 := by ring
        _ ≤ 9 * Real.rpow (bracketBump w) (3 / 2 : ℝ) := by
          gcongr
          exact thetaTOffcenter_bracket_sq_le_three_halves w
    calc
      bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
          bracketBump (v - t * R) ^ 2 *
            (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) := by
        gcongr
      _ = (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
            bracketBump (v - t * R) ^ 2 := by ring
  have hint : ∫ t : ℝ in Set.Icc 1 2,
      bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
      (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) * (2 * R⁻¹) := by
    calc
      ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
          ∫ t : ℝ in Set.Icc 1 2,
            (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
              bracketBump (v - t * R) ^ 2 := by
        apply MeasureTheory.setIntegral_mono_of_nonneg
        · exact fun _ _ ↦ mul_nonneg (sq_nonneg _) (sq_nonneg _)
        · exact fun t ht ↦ hpoint t ht
        · exact (thetaTOffcenter_integrable_shift R v hR).const_mul _ |>.integrableOn
      _ = (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
          ∫ t : ℝ in Set.Icc 1 2, bracketBump (v - t * R) ^ 2 := by
        rw [integral_const_mul]
      _ ≤ (9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) * (2 * R⁻¹) := by
        exact mul_le_mul_of_nonneg_left (thetaTOffcenter_mass R v hR)
          (mul_nonneg (by norm_num) (Real.rpow_nonneg (thetaTOffcenter_bracket_pos w).le _))
  calc
    Real.rpow R (-(1 / 2 : ℝ)) *
        ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v - t * R) ^ 2 * bracketBump (w - t * R) ^ 2 ≤
        Real.rpow R (-(1 / 2 : ℝ)) *
          ((9 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) * (2 * R⁻¹)) := by
      exact mul_le_mul_of_nonneg_left hint (Real.rpow_nonneg hR.le _)
    _ = (18 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
        (Real.rpow R (-(1 / 2 : ℝ)) * R⁻¹) := by ring
    _ = (18 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
        Real.rpow R (-(3 / 2 : ℝ)) := by rw [thetaTOffcenter_combine R hR]
    _ ≤ (18 * Real.rpow (bracketBump w) (3 / 2 : ℝ)) *
        (Real.rpow (7 / 2 : ℝ) (3 / 2 : ℝ) *
          Real.rpow (bracketBump v) (3 / 2 : ℝ)) := by
      exact mul_le_mul_of_nonneg_left hscale
        (mul_nonneg (by norm_num) (Real.rpow_nonneg (thetaTOffcenter_bracket_pos w).le _))
    _ = (18 * Real.rpow (7 / 2 : ℝ) (3 / 2 : ℝ)) *
        (Real.rpow (bracketBump v) (3 / 2 : ℝ) *
          Real.rpow (bracketBump w) (3 / 2 : ℝ)) := by ring
    _ ≤ 126 * (Real.rpow (bracketBump v) (3 / 2 : ℝ) *
          Real.rpow (bracketBump w) (3 / 2 : ℝ)) := by
      apply mul_le_mul_of_nonneg_right
      · nlinarith [thetaTOffcenter_rpow_seven_halves]
      · exact mul_nonneg (Real.rpow_nonneg (thetaTOffcenter_bracket_pos v).le _)
          (Real.rpow_nonneg (thetaTOffcenter_bracket_pos w).le _)

theorem thetaTOffcenter_two_small (R v₀ v₁ : ℝ) (hR : 0 < R) (hRtwo : 2 ≤ R)
    (h₀ : ¬ 3 * R ≤ |v₀|) (h₁ : ¬ 3 * R ≤ |v₁|) :
    Real.rpow R (-(1 / 2 : ℝ)) *
        ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
      133 * (Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
        Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
  have h₀small : |v₀| < 3 * R := lt_of_not_ge h₀
  have h₁small : |v₁| < 3 * R := lt_of_not_ge h₁
  have hsum : 1 + |v₀ + v₁| ≤ (13 / 2 : ℝ) * R := by
    nlinarith [abs_add_le v₀ v₁]
  have hscale : Real.rpow R (-(3 / 2 : ℝ)) ≤
      Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
        Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) :=
    thetaTOffcenter_scale R (13 / 2 : ℝ) (v₀ + v₁) hR (by norm_num) hsum
  have hpoint (t : ℝ) :
      bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
        2 * bracketBump (v₀ - v₁) ^ 2 *
          (bracketBump (v₀ - t * R) ^ 2 + bracketBump (v₁ - t * R) ^ 2) := by
    have h := thetaTOffcenter_two_point (v₀ - t * R) (v₁ - t * R)
    convert h using 1; ring_nf
  have hI₀ : Integrable (fun t : ℝ ↦ bracketBump (v₀ - t * R) ^ 2) :=
    thetaTOffcenter_integrable_shift R v₀ hR
  have hI₁ : Integrable (fun t : ℝ ↦ bracketBump (v₁ - t * R) ^ 2) :=
    thetaTOffcenter_integrable_shift R v₁ hR
  have hint : ∫ t : ℝ in Set.Icc 1 2,
      bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
      8 * bracketBump (v₀ - v₁) ^ 2 * R⁻¹ := by
    calc
      ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
          ∫ t : ℝ in Set.Icc 1 2,
            2 * bracketBump (v₀ - v₁) ^ 2 *
              (bracketBump (v₀ - t * R) ^ 2 + bracketBump (v₁ - t * R) ^ 2) := by
        apply MeasureTheory.setIntegral_mono_of_nonneg
        · exact fun _ _ ↦ mul_nonneg (sq_nonneg _) (sq_nonneg _)
        · exact fun t _ ↦ hpoint t
        · exact (((hI₀.add hI₁).const_mul _).integrableOn)
      _ = (2 * bracketBump (v₀ - v₁) ^ 2) *
          ((∫ t : ℝ in Set.Icc 1 2, bracketBump (v₀ - t * R) ^ 2) +
            (∫ t : ℝ in Set.Icc 1 2, bracketBump (v₁ - t * R) ^ 2)) := by
        rw [integral_const_mul, integral_add hI₀.integrableOn hI₁.integrableOn]
      _ ≤ (2 * bracketBump (v₀ - v₁) ^ 2) * (2 * R⁻¹ + 2 * R⁻¹) := by
        apply mul_le_mul_of_nonneg_left
        · exact add_le_add (thetaTOffcenter_mass R v₀ hR) (thetaTOffcenter_mass R v₁ hR)
        · exact mul_nonneg (by norm_num) (sq_nonneg _)
      _ = 8 * bracketBump (v₀ - v₁) ^ 2 * R⁻¹ := by ring
  calc
    Real.rpow R (-(1 / 2 : ℝ)) *
        ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
        Real.rpow R (-(1 / 2 : ℝ)) *
          (8 * bracketBump (v₀ - v₁) ^ 2 * R⁻¹) := by
      exact mul_le_mul_of_nonneg_left hint (Real.rpow_nonneg hR.le _)
    _ = (8 * bracketBump (v₀ - v₁) ^ 2) *
        (Real.rpow R (-(1 / 2 : ℝ)) * R⁻¹) := by ring
    _ = (8 * bracketBump (v₀ - v₁) ^ 2) *
        Real.rpow R (-(3 / 2 : ℝ)) := by rw [thetaTOffcenter_combine R hR]
    _ ≤ (8 * bracketBump (v₀ - v₁) ^ 2) *
        (Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
          Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ)) := by
      exact mul_le_mul_of_nonneg_left hscale (mul_nonneg (by norm_num) (sq_nonneg _))
    _ ≤ (8 * Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ)) *
        (Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
          Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
      have hsq := thetaTOffcenter_bracket_sq_le_three_halves (v₀ - v₁)
      calc
        8 * bracketBump (v₀ - v₁) ^ 2 *
            (Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ)) =
            (8 * Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ)) *
                bracketBump (v₀ - v₁) ^ 2 := by ring
        _ ≤ (8 * Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ)) *
                Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ) := by
          apply mul_le_mul_of_nonneg_left hsq
          exact mul_nonneg
            (mul_nonneg (by norm_num) (Real.rpow_nonneg (by norm_num) _))
            (Real.rpow_nonneg (thetaTOffcenter_bracket_pos (v₀ + v₁)).le _)
        _ = 8 * Real.rpow (13 / 2 : ℝ) (3 / 2 : ℝ) *
            (Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
              Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by ring
    _ ≤ 133 * (Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
          Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
      apply mul_le_mul_of_nonneg_right
      · nlinarith [thetaTOffcenter_rpow_thirteen_halves]
      · exact mul_nonneg (Real.rpow_nonneg (thetaTOffcenter_bracket_pos (v₀ + v₁)).le _)
          (Real.rpow_nonneg (thetaTOffcenter_bracket_pos (v₀ - v₁)).le _)


/--
**Lemma.**

Let $k\le-1$. Then for every $v\in\mathbb{R}^2$,

$$
2^{k/2}\int_1^2
\langle v_0-t2^{-k}\rangle^2
\langle v_1-t2^{-k}\rangle^2\,dt
\le C_{\text{lem:thetat\_offcenter}}
\left(
\langle v_0\rangle^{3/2}\langle v_1\rangle^{3/2}
+
\langle v_0+v_1\rangle^{3/2}\langle v_0-v_1\rangle^{3/2}
\right),
$$

where

$$
C_{\text{lem:thetat\_offcenter}}=133.
$$

See also `Auto.thetaTOffcenter`.
-/
theorem thetaTOffcenter (k : ℤ) (hk : k ≤ -1) (v₀ v₁ : ℝ) :
    Real.rpow 2 ((k : ℝ) / 2) *
        ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v₀ - t * ((2 : ℝ) ^ (-k))) ^ 2 *
            bracketBump (v₁ - t * ((2 : ℝ) ^ (-k))) ^ 2 ≤
      C_thetaTOffcenter *
        (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
            Real.rpow (bracketBump v₁) (3 / 2 : ℝ) +
          Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
            Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
  rw [C_thetaTOffcenter]
  let R : ℝ := (2 : ℝ) ^ (-k)
  have hR : 0 < R := by
    dsimp [R]
    exact zpow_pos (by norm_num) _
  have hRtwo : 2 ≤ R := by
    dsimp [R]
    calc
      2 = (2 : ℝ) ^ (1 : ℤ) := by norm_num
      _ ≤ (2 : ℝ) ^ (-k) := by
        apply zpow_le_zpow_right₀ (by norm_num)
        omega
  have hlead : Real.rpow 2 ((k : ℝ) / 2) =
      Real.rpow R (-(1 / 2 : ℝ)) := by
    simpa only [R] using thetaTOffcenter_lead k
  have hA : 0 ≤ Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
      Real.rpow (bracketBump v₁) (3 / 2 : ℝ) :=
    mul_nonneg (Real.rpow_nonneg (thetaTOffcenter_bracket_pos v₀).le _)
      (Real.rpow_nonneg (thetaTOffcenter_bracket_pos v₁).le _)
  have hC : 0 ≤ Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
      Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ) :=
    mul_nonneg (Real.rpow_nonneg (thetaTOffcenter_bracket_pos (v₀ + v₁)).le _)
      (Real.rpow_nonneg (thetaTOffcenter_bracket_pos (v₀ - v₁)).le _)
  change Real.rpow 2 ((k : ℝ) / 2) *
      ∫ t : ℝ in Set.Icc 1 2,
        bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤ _
  rw [hlead]
  by_cases h₀ : 3 * R ≤ |v₀|
  · by_cases h₁ : 3 * R ≤ |v₁|
    · have hpoint (t : ℝ) (ht : t ∈ Set.Icc 1 2) :
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
            54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
              Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
        have hlarge₀ := thetaTOffcenter_large R v₀ t hR h₀ ht
        have hlarge₁ := thetaTOffcenter_large R v₁ t hR h₁ ht
        have hp₀ : Real.rpow (bracketBump (v₀ - t * R)) (3 / 2 : ℝ) ≤
            Real.rpow (3 * bracketBump v₀) (3 / 2 : ℝ) :=
          Real.rpow_le_rpow (thetaTOffcenter_bracket_pos _).le hlarge₀ (by norm_num)
        have hp₁ : bracketBump (v₁ - t * R) ^ 2 ≤
            9 * Real.rpow (bracketBump v₁) (3 / 2 : ℝ) := by
          calc
            bracketBump (v₁ - t * R) ^ 2 ≤ (3 * bracketBump v₁) ^ 2 := by
              exact pow_le_pow_left₀ (thetaTOffcenter_bracket_pos _).le hlarge₁ 2
            _ = 9 * bracketBump v₁ ^ 2 := by ring
            _ ≤ 9 * Real.rpow (bracketBump v₁) (3 / 2 : ℝ) := by
              gcongr
              exact thetaTOffcenter_bracket_sq_le_three_halves v₁
        calc
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
              Real.rpow (bracketBump (v₀ - t * R)) (3 / 2 : ℝ) *
                bracketBump (v₁ - t * R) ^ 2 := by
            gcongr
            exact thetaTOffcenter_bracket_sq_le_three_halves _
          _ ≤ Real.rpow (3 * bracketBump v₀) (3 / 2 : ℝ) *
                (9 * Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
            exact mul_le_mul hp₀ hp₁ (sq_nonneg _) (Real.rpow_nonneg
              (mul_nonneg (by norm_num) (thetaTOffcenter_bracket_pos v₀).le) _)
          _ = (9 * Real.rpow 3 (3 / 2 : ℝ)) *
              (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
            have hmul : Real.rpow (3 * bracketBump v₀) (3 / 2 : ℝ) =
                Real.rpow 3 (3 / 2 : ℝ) *
                  Real.rpow (bracketBump v₀) (3 / 2 : ℝ) :=
              Real.mul_rpow (by norm_num) (thetaTOffcenter_bracket_pos v₀).le
            rw [hmul]
            ring
          _ ≤ 54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
            gcongr
            nlinarith [thetaTOffcenter_rpow_three]
      have hint : ∫ t : ℝ in Set.Icc 1 2,
          bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
          54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
            Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
        calc
          ∫ t : ℝ in Set.Icc 1 2,
              bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
              ∫ _t : ℝ in Set.Icc 1 2,
                54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                  Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
            apply MeasureTheory.setIntegral_mono_of_nonneg
            · exact fun _ _ ↦ mul_nonneg (sq_nonneg _) (sq_nonneg _)
            · exact fun t ht ↦ hpoint t ht
            · exact integrableOn_const (measure_Icc_lt_top.ne)
          _ = 54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := by
            norm_num [MeasureTheory.setIntegral_const, Real.volume_real_Icc_of_le]
      have hhalf : Real.rpow R (-(1 / 2 : ℝ)) ≤ 1 :=
        Real.rpow_le_one_of_one_le_of_nonpos (by linarith) (by norm_num)
      calc
        Real.rpow R (-(1 / 2 : ℝ)) *
            ∫ t : ℝ in Set.Icc 1 2,
              bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
            Real.rpow R (-(1 / 2 : ℝ)) *
              (54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ))) := by
              exact mul_le_mul_of_nonneg_left hint (Real.rpow_nonneg hR.le _)
        _ ≤ 1 * (54 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ))) := by
              gcongr
        _ ≤ 133 *
            (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ) +
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
                Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
          nlinarith
    · have hsmall := thetaTOffcenter_one_small R v₁ v₀ hR hRtwo h₁ h₀
      calc
        Real.rpow R (-(1 / 2 : ℝ)) *
            ∫ t : ℝ in Set.Icc 1 2,
              bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 =
            Real.rpow R (-(1 / 2 : ℝ)) *
              ∫ t : ℝ in Set.Icc 1 2,
                bracketBump (v₁ - t * R) ^ 2 * bracketBump (v₀ - t * R) ^ 2 := by
              congr 1
              apply integral_congr_ae
              filter_upwards [] with t
              ring
        _ ≤ 126 * (Real.rpow (bracketBump v₁) (3 / 2 : ℝ) *
              Real.rpow (bracketBump v₀) (3 / 2 : ℝ)) := hsmall
        _ ≤ 133 *
            (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ) +
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
                Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
          nlinarith
  · by_cases h₁ : 3 * R ≤ |v₁|
    · have hsmall := thetaTOffcenter_one_small R v₀ v₁ hR hRtwo h₀ h₁
      calc
        Real.rpow R (-(1 / 2 : ℝ)) *
            ∫ t : ℝ in Set.Icc 1 2,
              bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
            126 * (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
              Real.rpow (bracketBump v₁) (3 / 2 : ℝ)) := hsmall
        _ ≤ 133 *
            (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ) +
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
                Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
          nlinarith
    · have hsmall := thetaTOffcenter_two_small R v₀ v₁ hR hRtwo h₀ h₁
      calc
        Real.rpow R (-(1 / 2 : ℝ)) *
            ∫ t : ℝ in Set.Icc 1 2,
              bracketBump (v₀ - t * R) ^ 2 * bracketBump (v₁ - t * R) ^ 2 ≤
            133 * (Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
              Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := hsmall
        _ ≤ 133 *
            (Real.rpow (bracketBump v₀) (3 / 2 : ℝ) *
                Real.rpow (bracketBump v₁) (3 / 2 : ℝ) +
              Real.rpow (bracketBump (v₀ + v₁)) (3 / 2 : ℝ) *
                Real.rpow (bracketBump (v₀ - v₁)) (3 / 2 : ℝ)) := by
          nlinarith



/--
**Lemma (constant $C_{\text{lem:thetat\_offcenter}}$).**

$$
C_{\text{lem:thetat\_offcenter}}\le133.
$$

See also `Auto.thetaTOffcenter`.
-/
theorem constantOffCenterBump : C_thetaTOffcenter ≤ 133 := by
  norm_num [C_thetaTOffcenter]

/--
The one-dimensional $L^1$-normalized dilation used in Lemma
`Auto.integralFct`.
-/
noncomputable def aux_bf_realRescaled (t : ℝ) (psi : ℝ → ℝ) : ℝ → ℝ :=
  fun x ↦ t⁻¹ * psi (t⁻¹ * x)

/--
The tensor kernel defined by the integral in Lemma
`Auto.integralFct`.
-/
noncomputable def integralFctKernel (psi : ℝ → ℝ) :
    EuclideanSpace ℝ (Fin 2) → ℝ :=
  fun u ↦ ∫ t : ℝ in Set.Icc 1 2,
    aux_bf_realRescaled t psi (u 0) * aux_bf_realRescaled t psi (u 1) * t⁻¹

/-- The $L^1$-normalized two-dimensional dilation of `integralFctKernel`. -/
noncomputable def aux_integralFctKernelAtScale (s : ℝ) (psi : ℝ → ℝ) :
    EuclideanSpace ℝ (Fin 2) → ℝ :=
  rescaled s (integralFctKernel psi)

/--
The frequency set in the support conclusion of Lemma
`Auto.integralFct`.
-/
noncomputable def aux_integralFctBand (ell : ℤ) : Set ℝ :=
  Set.Icc (-((2 : ℝ) ^ (-ell))) (-((2 : ℝ) ^ (-3 - ell))) ∪
    Set.Icc ((2 : ℝ) ^ (-3 - ell)) ((2 : ℝ) ^ (-ell))

/-- The one-dimensional annulus convention used in `integralFct`. -/
def aux_annulusOne (r R : ℝ) : Set ℝ :=
  {xi | r / R ≤ |xi| ∧ |xi| ≤ R * r}

/-- The coordinatewise square of a one-dimensional frequency set. -/
def aux_productSet (s : Set ℝ) : Set (EuclideanSpace ℝ (Fin 2)) :=
  {xi | xi 0 ∈ s ∧ xi 1 ∈ s}

/--
The coordinate swap on $mathbb R^2$ used in the symmetry assertion of
Lemma `Auto.integralFct`.
-/
noncomputable def aux_swapTwo (u : EuclideanSpace ℝ (Fin 2)) :
    EuclideanSpace ℝ (Fin 2) :=
  WithLp.toLp 2 ![u 1, u 0]

/--
A bounded measurable real function, in the sense needed by the Lebesgue-integral
positivity statements in Lemmas `Auto.integralFct` and
`Auto.phiPosV2`.
-/
def aux_bounded (f : ℝ → ℝ) : Prop :=
  Measurable f ∧ Bornology.IsBounded (Set.range f)

/--
Auxiliary scaling identity for the Fourier-support part of
`integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_realRescaled_fourier (t : ℝ) (ht : 0 < t) (f : ℝ → ℝ) (xi : ℝ) :
    FourierTransform.fourier (fun x : ℝ => (aux_bf_realRescaled t f x : ℂ)) xi =
      FourierTransform.fourier (fun x : ℝ => (f x : ℂ)) (t * xi) := by
  rw [Real.fourier_real_eq_integral_exp_smul,
    Real.fourier_real_eq_integral_exp_smul]
  let g : ℝ → ℂ := fun q => (f q : ℂ) *
    Complex.exp (-((2 : ℂ) * Real.pi * Complex.I * (q : ℂ) * ((t * xi : ℝ) : ℂ)))
  calc
    (∫ x : ℝ, Complex.exp (↑(-2 * Real.pi * x * xi) * Complex.I) •
        (aux_bf_realRescaled t f x : ℂ)) = ∫ x : ℝ, (t⁻¹ : ℂ) * g (t⁻¹ * x) := by
      apply integral_congr_ae
      filter_upwards [] with x
      dsimp [g, aux_bf_realRescaled]
      have hphase : Complex.exp (↑(-2 * Real.pi * x * xi) * Complex.I) =
          Complex.exp (-((2 : ℂ) * Real.pi * Complex.I * ((t⁻¹ * x : ℝ) : ℂ) *
            ((t * xi : ℝ) : ℂ))) := by
        congr 1
        push_cast
        field_simp [ne_of_gt ht]
      rw [hphase]
      push_cast
      ring
    _ = (t⁻¹ : ℂ) * ∫ x : ℝ, g (t⁻¹ * x) := by rw [integral_const_mul]
    _ = (t⁻¹ : ℂ) * (|t| • ∫ y : ℝ, g y) := by
      rw [Measure.integral_comp_inv_mul_left]
    _ = ∫ y : ℝ, g y := by
      rw [abs_of_pos ht]
      field_simp [ne_of_gt ht]
      rw [Complex.real_smul]
    _ = ∫ x : ℝ, Complex.exp (↑(-2 * Real.pi * x * (t * xi)) * Complex.I) •
        (f x : ℂ) := by
      apply integral_congr_ae
      filter_upwards [] with x
      dsimp [g]
      push_cast
      ring_nf

/-! ### Smooth compact parameter integrals

The scale variable in `integralFctKernel` ranges over `[1, 2]`.  The following
calculus helpers keep the differentiation-under-the-integral argument
local, while avoiding an unnecessary Bochner integral in Schwartz space. -/

universe u

noncomputable def aux_partialFDeriv
    {E V : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup V] [NormedSpace ℝ V]
    (F : E → ℝ → V) : E → ℝ → E →L[ℝ] V :=
  fun x t => (fderiv ℝ F.uncurry (x, t)).comp (ContinuousLinearMap.inl ℝ E ℝ)

theorem aux_partialFDeriv_contDiffOn
    {E V : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup V] [NormedSpace ℝ V]
    (F : E → ℝ → V) (N : ℕ)
    (hF : ContDiffOn ℝ (N + 1) F.uncurry (univ ×ˢ Ioi (0 : ℝ))) :
    ContDiffOn ℝ N (aux_partialFDeriv F).uncurry (univ ×ˢ Ioi (0 : ℝ)) := by
  let L : (E × ℝ →L[ℝ] V) →L[ℝ] E →L[ℝ] V :=
    (ContinuousLinearMap.compL ℝ E (E × ℝ) V).flip
      (ContinuousLinearMap.inl ℝ E ℝ)
  have hopen : IsOpen ((univ : Set E) ×ˢ Ioi (0 : ℝ)) :=
    isOpen_univ.prod isOpen_Ioi
  have hderiv : ContDiffOn ℝ N (fderiv ℝ F.uncurry) (univ ×ˢ Ioi (0 : ℝ)) :=
    hF.fderiv_of_isOpen hopen (m := N) (by norm_num)
  have hcomp : ContDiffOn ℝ N (fun p : E × ℝ => L (fderiv ℝ F.uncurry p))
      (univ ×ˢ Ioi (0 : ℝ)) :=
    L.contDiff.comp_contDiffOn hderiv
  change ContDiffOn ℝ N (fun p : E × ℝ =>
    (fderiv ℝ F.uncurry p).comp (ContinuousLinearMap.inl ℝ E ℝ))
    (univ ×ˢ Ioi (0 : ℝ))
  exact hcomp

theorem aux_partialFDeriv_hasFDerivAt_of_contDiffOn
    {E V : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    [NormedAddCommGroup V] [NormedSpace ℝ V]
    (F : E → ℝ → V)
    (hF : ContDiffOn ℝ 1 F.uncurry (univ ×ˢ Ioi (0 : ℝ)))
    (x : E) (t : ℝ) (ht : 0 < t) :
    HasFDerivAt (fun y => F y t) (aux_partialFDeriv F x t) x := by
  have hopen : IsOpen ((univ : Set E) ×ˢ Ioi (0 : ℝ)) :=
    isOpen_univ.prod isOpen_Ioi
  have hpt : (x, t) ∈ (univ : Set E) ×ˢ Ioi (0 : ℝ) := ⟨mem_univ _, ht⟩
  have hd : DifferentiableAt ℝ F.uncurry (x, t) :=
    (hF.differentiableOn one_ne_zero).differentiableAt (hopen.mem_nhds hpt)
  have htotal : HasFDerivAt F.uncurry (fderiv ℝ F.uncurry (x, t)) (x, t) :=
    hd.hasFDerivAt
  have hin : HasFDerivAt (fun y : E => (y, t))
      (ContinuousLinearMap.inl ℝ E ℝ) x := by
    simpa using ((ContinuousLinearMap.inl ℝ E ℝ).hasFDerivAt (x := x)).add_const (0, t)
  change HasFDerivAt (fun y => F y t)
    ((fderiv ℝ F.uncurry (x, t)).comp (ContinuousLinearMap.inl ℝ E ℝ)) x
  convert htotal.comp x hin using 1
  funext y
  rfl

theorem aux_hasFDerivAt_setIntegral_Icc_of_continuousOn
    {E V : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [ProperSpace E]
    [NormedAddCommGroup V] [NormedSpace ℝ V] [CompleteSpace V]
    (F : E → ℝ → V) (D : E → ℝ → E →L[ℝ] V)
    (hF : ContinuousOn F.uncurry (univ ×ˢ Ioi (0 : ℝ)))
    (hD : ContinuousOn D.uncurry (univ ×ˢ Ioi (0 : ℝ)))
    (hderiv : ∀ x t, 0 < t → HasFDerivAt (fun y => F y t) (D x t) x)
    (x : E) :
    HasFDerivAt (fun y => ∫ t : ℝ in Icc (1 : ℝ) 2, F y t)
      (∫ t : ℝ in Icc (1 : ℝ) 2, D x t) x := by
  have hsliceF (y : E) : ContinuousOn (F y) (Icc (1 : ℝ) 2) := by
    refine hF.comp (continuous_const.prodMk continuous_id).continuousOn ?_
    intro t ht
    exact ⟨mem_univ _, lt_of_lt_of_le zero_lt_one ht.1⟩
  have hsliceD (y : E) : ContinuousOn (D y) (Icc (1 : ℝ) 2) := by
    refine hD.comp (continuous_const.prodMk continuous_id).continuousOn ?_
    intro t ht
    exact ⟨mem_univ _, lt_of_lt_of_le zero_lt_one ht.1⟩
  have hsub : (Metric.closedBall x 1 : Set E) ×ˢ Icc (1 : ℝ) 2 ⊆
      (univ : Set E) ×ˢ Ioi (0 : ℝ) := by
    rintro ⟨y, t⟩ ⟨hy, ht⟩
    exact ⟨mem_univ _, lt_of_lt_of_le zero_lt_one ht.1⟩
  obtain ⟨C, hC⟩ :=
    ((ProperSpace.isCompact_closedBall x 1).prod isCompact_Icc).bddAbove_image
      (hD.mono hsub).norm
  let s : Set E := Metric.ball x 1
  have hs : s ∈ nhds x := by
    exact Metric.ball_mem_nhds _ zero_lt_one
  have hFmeas : ∀ᶠ y in nhds x,
      AEStronglyMeasurable (F y) (volume.restrict (Icc (1 : ℝ) 2)) := by
    filter_upwards [] with y
    exact (hsliceF y).aestronglyMeasurable measurableSet_Icc
  have hFint : Integrable (F x) (volume.restrict (Icc (1 : ℝ) 2)) := by
    exact (hsliceF x).integrableOn_compact isCompact_Icc
  have hDmeas : AEStronglyMeasurable (D x) (volume.restrict (Icc (1 : ℝ) 2)) := by
    exact (hsliceD x).aestronglyMeasurable measurableSet_Icc
  have hbound : ∀ᵐ t : ℝ ∂(volume.restrict (Icc (1 : ℝ) 2)),
      ∀ y ∈ s, ‖D y t‖ ≤ (fun _ : ℝ => C) t := by
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht y hy
    apply hC
    refine ⟨(y, t), ?_, ?_⟩
    · constructor
      · change dist y x < 1 at hy
        exact Metric.mem_closedBall.mpr hy.le
      · exact ht
    · rfl
  have hCint : Integrable (fun _ : ℝ => C) (volume.restrict (Icc (1 : ℝ) 2)) := by
    exact continuous_const.integrableOn_Icc
  have hdiff : ∀ᵐ t : ℝ ∂(volume.restrict (Icc (1 : ℝ) 2)),
      ∀ y ∈ s, HasFDerivAt (fun y => F y t) (D y t) y := by
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht y hy
    exact hderiv y t (lt_of_lt_of_le zero_lt_one ht.1)
  exact hasFDerivAt_integral_of_dominated_of_fderiv_le hs hFmeas hFint hDmeas hbound hCint hdiff

theorem aux_contDiff_setIntegral_Icc_of_contDiffOn
    {E V : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E] [ProperSpace E]
    [NormedAddCommGroup V] [NormedSpace ℝ V] [CompleteSpace V]
    (F : E → ℝ → V) (N : ℕ)
    (hF : ContDiffOn ℝ (N + 1) F.uncurry (univ ×ˢ Ioi (0 : ℝ))) :
    ContDiff ℝ N (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) := by
  induction N generalizing V with
  | zero =>
      have hderiv := aux_hasFDerivAt_setIntegral_Icc_of_continuousOn F
        (aux_partialFDeriv F) hF.continuousOn
        (aux_partialFDeriv_contDiffOn F 0 (by simpa using hF)).continuousOn
        (aux_partialFDeriv_hasFDerivAt_of_contDiffOn F hF)
      have hdiff : Differentiable ℝ
          (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) :=
        fun x => (hderiv x).differentiableAt
      exact contDiff_zero.mpr hdiff.continuous
  | succ N ih =>
      have hFone : ContDiffOn ℝ 1 F.uncurry (univ ×ˢ Ioi (0 : ℝ)) :=
        hF.of_le (by norm_num)
      have hD : ContDiffOn ℝ (N + 1) (aux_partialFDeriv F).uncurry
          (univ ×ˢ Ioi (0 : ℝ)) := by
        exact aux_partialFDeriv_contDiffOn F (N + 1) (by
          simpa [Nat.succ_eq_add_one, Nat.add_assoc] using hF)
      have hIntD : ContDiff ℝ N
          (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, aux_partialFDeriv F x t) :=
        ih (aux_partialFDeriv F) hD
      have hdiff : Differentiable ℝ
          (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) := by
        intro x
        exact (aux_hasFDerivAt_setIntegral_Icc_of_continuousOn F (aux_partialFDeriv F)
          hFone.continuousOn hD.continuousOn
          (aux_partialFDeriv_hasFDerivAt_of_contDiffOn F hFone) x).differentiableAt
      have hderiv : fderiv ℝ (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) =
          fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, aux_partialFDeriv F x t := by
        funext x
        exact (aux_hasFDerivAt_setIntegral_Icc_of_continuousOn F (aux_partialFDeriv F)
          hFone.continuousOn hD.continuousOn
          (aux_partialFDeriv_hasFDerivAt_of_contDiffOn F hFone) x).fderiv
      have htarget : ContDiff ℝ ((N : WithTop ℕ∞) + 1)
          (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) := by
        rw [contDiff_succ_iff_fderiv]
        refine ⟨hdiff, ?_, ?_⟩
        · simp
        · rw [hderiv]
          exact hIntD
      simpa only [Nat.cast_add, Nat.cast_one] using htarget

theorem aux_contDiff_infty_setIntegral_Icc_of_contDiffOn
    {E V : Type u} [NormedAddCommGroup E] [NormedSpace ℝ E] [ProperSpace E]
    [NormedAddCommGroup V] [NormedSpace ℝ V] [CompleteSpace V]
    (F : E → ℝ → V)
    (hF : ContDiffOn ℝ (⊤ : ℕ∞) F.uncurry (univ ×ˢ Ioi (0 : ℝ))) :
    ContDiff ℝ (⊤ : ℕ∞)
      (fun x => ∫ t : ℝ in Icc (1 : ℝ) 2, F x t) := by
  rw [contDiff_infty]
  intro N
  have hN : (N + 1 : ℕ∞) ≤ ⊤ := le_top
  exact aux_contDiff_setIntegral_Icc_of_contDiffOn F N
    (hF.of_le (by exact_mod_cast hN))

/--
The product Fourier factorization used in the support calculation of
`integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_fourier_tensor_two (f g : ℝ → ℝ) (xi : EuclideanSpace ℝ (Fin 2)) :
    FourierTransform.fourier (fun u : EuclideanSpace ℝ (Fin 2) =>
      (f (u 0) * g (u 1) : ℂ)) xi =
    FourierTransform.fourier (fun x : ℝ => (f x : ℂ)) (xi 0) *
      FourierTransform.fourier (fun x : ℝ => (g x : ℂ)) (xi 1) := by
  rw [Real.fourier_eq', Real.fourier_eq', Real.fourier_eq']
  rw [← (PiLp.volume_preserving_toLp (Fin 2)).integral_comp
    (MeasurableEquiv.toLp 2 _).measurableEmbedding]
  let F : Fin 2 → ℝ → ℂ := fun i x =>
    if i = 0 then
      Complex.exp (↑(-2 * Real.pi * x * xi 0) * Complex.I) * (f x : ℂ)
    else Complex.exp (↑(-2 * Real.pi * x * xi 1) * Complex.I) * (g x : ℂ)
  calc
    (∫ x : Fin 2 → ℝ,
      Complex.exp (↑(-2 * Real.pi * ⟪WithLp.toLp 2 x, xi⟫) * Complex.I) •
        ((f ((WithLp.toLp 2 x) 0) : ℂ) * (g ((WithLp.toLp 2 x) 1) : ℂ))) =
      ∫ x : Fin 2 → ℝ, ∏ i, F i (x i) := by
        apply integral_congr_ae
        filter_upwards [] with x
        dsimp [F]
        rw [Fin.prod_univ_two]
        rw [PiLp.inner_apply, Fin.sum_univ_two]
        simp only [RCLike.inner_apply, starRingEnd_apply, star_trivial, neg_mul,
          Complex.ofReal_neg, Complex.ofReal_add, Complex.ofReal_mul, Complex.ofReal_ofNat,
          Fin.isValue, ↓reduceIte, one_ne_zero]
        have hphase :
            Complex.exp (-(2 * (Real.pi : ℂ) *
              ((xi 0 : ℂ) * (x 0 : ℂ) + (xi 1 : ℂ) * (x 1 : ℂ)) * Complex.I)) =
              Complex.exp (-(2 * (Real.pi : ℂ) * (x 0 : ℂ) * (xi 0 : ℂ) * Complex.I)) *
                Complex.exp (-(2 * (Real.pi : ℂ) * (x 1 : ℂ) * (xi 1 : ℂ) * Complex.I)) := by
          rw [← Complex.exp_add]
          congr 1
          ring
        rw [hphase]
        ring
    _ = (∫ x, F 0 x) * ∫ x, F 1 x := by
      rw [MeasureTheory.integral_fin_nat_prod_volume_eq_prod]
      simp only [Fin.prod_univ_two]
    _ = _ := by
      dsimp [F]
      simp only [neg_mul, Fin.isValue, Complex.ofReal_neg, Complex.ofReal_mul,
        Complex.ofReal_ofNat, Real.ringHom_apply]
      apply congrArg₂ (· * ·)
      · apply integral_congr_ae
        filter_upwards [] with x
        ring_nf
      · apply integral_congr_ae
        filter_upwards [] with x
        ring_nf

/--
The Fourier transform of a two-coordinate tensor product factors into the
two one-dimensional Fourier transforms.  This exposes the calculation used in
the reduction argument without duplicating its Fubini proof.
-/
theorem aux_fourier_tensor_two_eq (f g : ℝ → ℝ) (xi : EuclideanSpace ℝ (Fin 2)) :
    FourierTransform.fourier (fun u : EuclideanSpace ℝ (Fin 2) =>
      (f (u 0) * g (u 1) : ℂ)) xi =
    FourierTransform.fourier (fun x : ℝ => (f x : ℂ)) (xi 0) *
      FourierTransform.fourier (fun x : ℝ => (g x : ℂ)) (xi 1) := by
  exact aux_fourier_tensor_two f g xi

/--
Integrability of the three-variable Fubini integrand in the positivity part of
`integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_integralFct_triple_integrable
    (psi : SchwartzMap ℝ ℝ) (s : ℝ) (hs : 0 < s)
    (f : ℝ → ℝ) (hf : Measurable f) (C : ℝ) (hC : ∀ x, |f x| ≤ C) :
    Integrable (fun q : ℝ × (ℝ × ℝ) =>
      (f q.2.1 * aux_bf_realRescaled (s * q.1) (fun x => psi x) q.2.1) *
        (f q.2.2 * aux_bf_realRescaled (s * q.1) (fun x => psi x) q.2.2) * q.1⁻¹)
      ((volume.restrict (Set.Icc 1 2)).prod volume) := by
  let μ : Measure ℝ := volume.restrict (Set.Icc 1 2)
  let : IsFiniteMeasure μ := by
    dsimp [μ]
    infer_instance
  let A : ℝ × ℝ → ℝ := fun tx =>
    f tx.2 * aux_bf_realRescaled (s * tx.1) (fun x => psi x) tx.2
  let H : ℝ × (ℝ × ℝ) → ℝ := fun q => A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹
  have hAmeas : Measurable A := by
    dsimp [A, aux_bf_realRescaled]
    fun_prop
  have hHmeas : Measurable H := by
    dsimp [H, A, aux_bf_realRescaled]
    fun_prop
  have hscaleNorm (a : ℝ) (ha : 0 < a) :
      ∫ x : ℝ, ‖aux_bf_realRescaled a (fun x => psi x) x‖ = ∫ x : ℝ, ‖psi x‖ := by
    rw [show (fun x : ℝ => ‖aux_bf_realRescaled a (fun x => psi x) x‖) =
        fun x => |a⁻¹| * ‖psi (a⁻¹ * x)‖ by
          funext x
          simp [aux_bf_realRescaled, norm_mul]]
    rw [integral_const_mul]
    rw [Measure.integral_comp_inv_mul_left (fun x : ℝ => ‖psi x‖) a]
    rw [smul_eq_mul]
    have hne : a ≠ 0 := ne_of_gt ha
    rw [abs_inv, abs_of_pos ha]
    field_simp
  have hAt (t : ℝ) (ht : 0 < t) : Integrable (fun x : ℝ => A (t, x)) := by
    have hst : 0 < s * t := mul_pos hs ht
    have hraw : Integrable (aux_bf_realRescaled (s * t) (fun x => psi x)) := by
      unfold aux_bf_realRescaled
      convert (psi.integrable.comp_mul_left' (inv_ne_zero hst.ne')).const_mul (s * t)⁻¹ using 1
    dsimp [A]
    refine hraw.bdd_mul hf.aestronglyMeasurable (c := C) ?_
    filter_upwards [] with x
    simpa [Real.norm_eq_abs] using hC x
  have hLbound (t : ℝ) (ht : 0 < t) :
      ∫ x : ℝ, ‖A (t, x)‖ ≤ C * ∫ x : ℝ, ‖psi x‖ := by
    have hst : 0 < s * t := mul_pos hs ht
    have hraw : Integrable (aux_bf_realRescaled (s * t) (fun x => psi x)) := by
      unfold aux_bf_realRescaled
      convert (psi.integrable.comp_mul_left' (inv_ne_zero hst.ne')).const_mul (s * t)⁻¹ using 1
    have hAt' := hAt t ht
    calc
      ∫ x : ℝ, ‖A (t, x)‖ ≤
          ∫ x : ℝ, C * ‖aux_bf_realRescaled (s * t) (fun x => psi x) x‖ := by
        apply integral_mono hAt'.norm (hraw.norm.const_mul C)
        intro x
        change ‖f x * aux_bf_realRescaled (s * t) (fun x => psi x) x‖ ≤ _
        rw [norm_mul]
        exact mul_le_mul_of_nonneg_right (by simpa [Real.norm_eq_abs] using hC x)
          (norm_nonneg _)
      _ = C * ∫ x : ℝ, ‖aux_bf_realRescaled (s * t) (fun x => psi x) x‖ := by
        rw [integral_const_mul]
      _ = C * ∫ x : ℝ, ‖psi x‖ := by rw [hscaleNorm _ hst]
  have hfixed : ∀ᵐ t : ℝ ∂μ, Integrable (fun xy : ℝ × ℝ => H (t, xy)) := by
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
    have htpos : 0 < t := lt_of_lt_of_le zero_lt_one ht.1
    have hprod : Integrable (fun xy : ℝ × ℝ => A (t, xy.1) * A (t, xy.2)) :=
      (hAt t htpos).mul_prod (hAt t htpos)
    dsimp [H]
    simpa [mul_assoc] using hprod.mul_const t⁻¹
  have houterMeas : AEStronglyMeasurable
      (fun t : ℝ => ∫ xy : ℝ × ℝ, ‖H (t, xy)‖) μ := by
    exact hHmeas.norm.aestronglyMeasurable.integral_prod_right'
  have hCnonneg : 0 ≤ C := by
    have := hC 0
    linarith [abs_nonneg (f 0)]
  have hDnonneg : 0 ≤ C * ∫ x : ℝ, ‖psi x‖ :=
    mul_nonneg hCnonneg (integral_nonneg fun _ => norm_nonneg _)
  have houterBound : ∀ᵐ t : ℝ ∂μ,
      ‖∫ xy : ℝ × ℝ, ‖H (t, xy)‖‖ ≤ (C * ∫ x : ℝ, ‖psi x‖) ^ 2 := by
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
    have htpos : 0 < t := lt_of_lt_of_le zero_lt_one ht.1
    have htinvle : t⁻¹ ≤ 1 := (inv_le_one₀ htpos).2 ht.1
    have hAt' := hAt t htpos
    have hprodNorm : Integrable (fun xy : ℝ × ℝ => ‖A (t, xy.1)‖ * ‖A (t, xy.2)‖) :=
      hAt'.norm.mul_prod hAt'.norm
    have hHnorm : Integrable (fun xy : ℝ × ℝ => ‖H (t, xy)‖) := by
      dsimp [H]
      have := hprodNorm.mul_const t⁻¹
      convert this using 1; simp [abs_of_pos htpos, mul_assoc]
    have hcalc : ∫ xy : ℝ × ℝ, ‖H (t, xy)‖ =
        (∫ x : ℝ, ‖A (t, x)‖) * (∫ x : ℝ, ‖A (t, x)‖) * t⁻¹ := by
      rw [show (fun xy : ℝ × ℝ => ‖H (t, xy)‖) =
          fun xy => (‖A (t, xy.1)‖ * ‖A (t, xy.2)‖) * t⁻¹ by
            funext xy
            simp [H, norm_mul, abs_of_pos htpos, mul_assoc]]
      rw [integral_mul_const]
      rw [show (∫ xy : ℝ × ℝ, ‖A (t, xy.1)‖ * ‖A (t, xy.2)‖) =
          (∫ x : ℝ, ‖A (t, x)‖) * ∫ x : ℝ, ‖A (t, x)‖ by
            simpa only [Measure.volume_eq_prod] using
              integral_prod_mul (fun x : ℝ => ‖A (t, x)‖) (fun x : ℝ => ‖A (t, x)‖)]
    have hLnonneg : 0 ≤ ∫ x : ℝ, ‖A (t, x)‖ := integral_nonneg fun _ => norm_nonneg _
    have hLle : ∫ x : ℝ, ‖A (t, x)‖ ≤ C * ∫ x : ℝ, ‖psi x‖ := hLbound t htpos
    rw [Real.norm_eq_abs, abs_of_nonneg (integral_nonneg fun _ => norm_nonneg _)]
    rw [hcalc]
    nlinarith
  have houter : Integrable (fun t : ℝ => ∫ xy : ℝ × ℝ, ‖H (t, xy)‖) μ :=
    Integrable.of_bound houterMeas ((C * ∫ x : ℝ, ‖psi x‖) ^ 2) houterBound
  have hH : Integrable H (μ.prod volume) :=
    (integrable_prod_iff hHmeas.aestronglyMeasurable).2 ⟨hfixed, houter⟩
  simpa [μ, H, A] using hH

/--
Rewriting the scaled kernel as the corresponding integral of one-dimensional
dilations, used in the positivity and Fourier-support parts of `integralFct`.
-/
theorem aux_integralFctKernelAtScale_eq
    (s : ℝ) (hs : s ≠ 0) (psi : ℝ → ℝ) (u : EuclideanSpace ℝ (Fin 2)) :
    aux_integralFctKernelAtScale s psi u =
      ∫ t : ℝ in Set.Icc 1 2,
        aux_bf_realRescaled (s * t) psi (u 0) *
          aux_bf_realRescaled (s * t) psi (u 1) * t⁻¹ := by
  unfold aux_integralFctKernelAtScale rescaled integralFctKernel
  rw [← MeasureTheory.integral_const_mul]
  apply integral_congr_ae
  filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
  have ht0 : t ≠ 0 := ne_of_gt (lt_of_lt_of_le zero_lt_one ht.1)
  simp only [aux_bf_realRescaled]
  simp only [PiLp.smul_apply, smul_eq_mul]
  field_simp [hs, ht0]

/--
Expand a nonzero dilation of `integralFctKernel` into its defining compact
scale integral.  This is the reusable scale/Fubini form of the kernel.
-/
theorem integralFctKernelAtScale_eq
    (s : ℝ) (hs : s ≠ 0) (psi : ℝ → ℝ) (u : EuclideanSpace ℝ (Fin 2)) :
    aux_integralFctKernelAtScale s psi u =
      ∫ t : ℝ in Set.Icc 1 2,
        aux_bf_realRescaled (s * t) psi (u 0) *
          aux_bf_realRescaled (s * t) psi (u 1) * t⁻¹ :=
  aux_integralFctKernelAtScale_eq s hs psi u

/--
The product-square form of the Fubini integral in the positivity part of
`integralFct` (Lemma `Auto.integralFct`) is nonnegative.
-/
theorem aux_integralFct_triple_nonnegative (A : ℝ × ℝ → ℝ)
    (hH : Integrable (fun q : ℝ × (ℝ × ℝ) =>
      A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹)
      ((volume.restrict (Set.Icc 1 2)).prod volume)) :
    0 ≤ ∫ q : ℝ × (ℝ × ℝ),
      A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹
        ∂((volume.restrict (Set.Icc 1 2)).prod volume) := by
  let μ : Measure ℝ := volume.restrict (Set.Icc 1 2)
  calc
    (∫ q : ℝ × (ℝ × ℝ), A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹ ∂(μ.prod volume)) =
        ∫ t : ℝ, ∫ xy : ℝ × ℝ, A (t, xy.1) * A (t, xy.2) * t⁻¹ ∂volume ∂μ := by
          simpa only [Measure.volume_eq_prod] using
            (integral_prod (fun q : ℝ × (ℝ × ℝ) =>
              A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹) hH)
    _ = ∫ t : ℝ, (∫ x : ℝ, A (t, x)) ^ 2 * t⁻¹ ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with t
      rw [integral_mul_const]
      rw [show (∫ xy : ℝ × ℝ, A (t, xy.1) * A (t, xy.2)) =
          (∫ x : ℝ, A (t, x)) * ∫ x : ℝ, A (t, x) by
        simpa only [Measure.volume_eq_prod] using
          integral_prod_mul (fun x : ℝ => A (t, x)) (fun x : ℝ => A (t, x))]
      ring
    _ ≥ 0 := by
      apply integral_nonneg_of_ae
      filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
      exact mul_nonneg (sq_nonneg _) (inv_nonneg.mpr (by linarith [ht.1]))

/--
Fubini interchange for the compact scale integral in the Fourier-support
calculation of `integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_fourier_setIntegral_swap
    {V} [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    [MeasurableSpace V] [BorelSpace V] [FiniteDimensional ℝ V]
    (k : ℝ → V → ℂ) (a b : ℝ) (xi : V)
    (h : Integrable (fun q : ℝ × V =>
      Complex.exp (↑(-2 * Real.pi * ⟪q.2, xi⟫) * Complex.I) • k q.1 q.2)
      ((volume.restrict (Set.Icc a b)).prod volume)) :
    FourierTransform.fourier (fun u : V => ∫ t in Set.Icc a b, k t u) xi =
      ∫ t in Set.Icc a b, FourierTransform.fourier (k t) xi := by
  simp_rw [Real.fourier_eq']
  simp_rw [← integral_smul]
  rw [← integral_integral_swap h]

/--
A version of `aux_fourier_setIntegral_swap` which obtains the harmless
Fourier phase integrability from the raw integrability hypothesis.
-/
theorem aux_fourier_setIntegral_swap_of_integrable
    {V} [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    [MeasurableSpace V] [BorelSpace V] [FiniteDimensional ℝ V]
    (k : ℝ → V → ℂ) (a b : ℝ) (xi : V)
    (h : Integrable (fun q : ℝ × V => k q.1 q.2)
      ((volume.restrict (Set.Icc a b)).prod volume)) :
    FourierTransform.fourier (fun u : V => ∫ t in Set.Icc a b, k t u) xi =
      ∫ t in Set.Icc a b, FourierTransform.fourier (k t) xi := by
  let e : ℝ × V → ℂ := fun q =>
    Complex.exp (↑(-2 * Real.pi * ⟪q.2, xi⟫) * Complex.I)
  have he : Continuous e := by
    dsimp [e]
    fun_prop
  have he_bound : ∀ q : ℝ × V, ‖e q‖ ≤ (1 : ℝ) := by
    intro q
    rw [show e q = Complex.exp (((-2 * Real.pi * ⟪q.2, xi⟫ : ℝ) : ℂ) * Complex.I) by rfl,
      Complex.norm_exp]
    norm_num
  have hp : Integrable (fun q : ℝ × V => e q * k q.1 q.2) _ :=
    h.bdd_mul he.aestronglyMeasurable (ae_of_all _ he_bound)
  apply aux_fourier_setIntegral_swap k a b xi
  simpa [e, smul_eq_mul] using hp

/--
The unit Fourier band, after a scale in `[1,2]`, lies in the band used by
`integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_integralFct_scale_band_mem (s t x : ℝ) (hs : 0 < s)
    (ht : t ∈ Set.Icc 1 2)
    (h : s * t * x ∈ Set.Icc (-1 : ℝ) (-(1 / 4 : ℝ)) ∪ Set.Icc (1 / 4 : ℝ) 1) :
    x ∈ Set.Icc (-s⁻¹) (-(1 / 8 : ℝ) * s⁻¹) ∪
      Set.Icc ((1 / 8 : ℝ) * s⁻¹) s⁻¹ := by
  have htpos : 0 < t := lt_of_lt_of_le zero_lt_one ht.1
  have hp : 0 < s * t := mul_pos hs htpos
  rcases h with hneg | hpos
  · left
    constructor
    · apply le_of_mul_le_mul_left _ hp
      calc
        (s * t) * (-s⁻¹) = -t := by field_simp [hs.ne']
        _ ≤ -1 := by linarith [ht.1]
        _ ≤ s * t * x := hneg.1
    · apply le_of_mul_le_mul_left _ hp
      calc
        s * t * x ≤ -(1 / 4 : ℝ) := hneg.2
        _ ≤ (s * t) * (-(1 / 8 : ℝ) * s⁻¹) := by
          have heq : (s * t) * (-(1 / 8 : ℝ) * s⁻¹) = -t / 8 := by
            field_simp [hs.ne']
          rw [heq]
          linarith [ht.2]
  · right
    constructor
    · apply le_of_mul_le_mul_left _ hp
      calc
        (s * t) * ((1 / 8 : ℝ) * s⁻¹) = t / 8 := by
          field_simp [hs.ne']
        _ ≤ 1 / 4 := by linarith [ht.2]
        _ ≤ s * t * x := hpos.1
    · apply le_of_mul_le_mul_left _ hp
      calc
        s * t * x ≤ 1 := hpos.2
        _ ≤ t := by linarith [ht.1]
        _ = (s * t) * s⁻¹ := by field_simp [hs.ne']

/--
A coordinate outside the scaled band forces the corresponding Fourier factor
to vanish in the support proof of `integralFct` (Lemma
`Auto.integralFct`).
-/
theorem aux_integralFct_fourier_zero_outside_band
    (psi : SchwartzMap ℝ ℝ)
    (hpsi : Function.support (FourierTransform.fourier (fun x : ℝ ↦ (psi x : ℂ))) ⊆
      Set.Icc (-1 : ℝ) (-(1 / 4 : ℝ)) ∪ Set.Icc (1 / 4 : ℝ) 1)
    (ell : ℤ) (t : ℝ) (ht : t ∈ Set.Icc 1 2) (x : ℝ)
    (hx : x ∉ aux_integralFctBand ell) :
    FourierTransform.fourier (fun y : ℝ => (psi y : ℂ))
      (((2 : ℝ) ^ ell) * t * x) = 0 := by
  by_contra hne
  apply hx
  have hmem := hpsi (Function.mem_support.mpr hne)
  have hs : 0 < (2 : ℝ) ^ ell := zpow_pos (by norm_num) _
  have hband := aux_integralFct_scale_band_mem ((2 : ℝ) ^ ell) t x hs ht hmem
  unfold aux_integralFctBand
  have hpow0 : (2 : ℝ) ^ (-ell) = ((2 : ℝ) ^ ell)⁻¹ := by rw [zpow_neg]
  have hpow3 : (2 : ℝ) ^ (-3 - ell) = (1 / 8 : ℝ) * ((2 : ℝ) ^ ell)⁻¹ := by
    rw [show (-3 - ell : ℤ) = (-3 : ℤ) + (-ell) by omega,
      zpow_add₀ (by norm_num : (2 : ℝ) ≠ 0), zpow_neg]
    norm_num
  rw [hpow0, hpow3]
  convert hband using 1; ring_nf

/-- The one-dimensional band in `integralFct` lies in its stated annulus. -/
theorem aux_band_subset_annulus (r : ℝ) (hr : 0 ≤ r) :
    Set.Icc (-r) (-(r / 8)) ∪ Set.Icc (r / 8) r ⊆
      {x : ℝ | r / 8 ≤ |x| ∧ |x| ≤ 8 * r} := by
  intro x hx
  rcases hx with hx | hx
  · have hxnonpos : x ≤ 0 := by linarith [hx.2]
    change r / 8 ≤ |x| ∧ |x| ≤ 8 * r
    rw [abs_of_nonpos hxnonpos]
    constructor <;> linarith [hx.1, hx.2]
  · have hxnonneg : 0 ≤ x := by linarith [hx.1]
    change r / 8 ≤ |x| ∧ |x| ≤ 8 * r
    rw [abs_of_nonneg hxnonneg]
    constructor
    · exact hx.1
    · nlinarith [hx.2, hr]

/--
The scale-integrated tensor kernel has nonnegative quadratic forms.  This is
the positivity assertion used by `integralFct` (Lemma
`Auto.integralFct`).
-/
theorem aux_integralFctKernelAtScale_nonnegative
    (psi : SchwartzMap ℝ ℝ) (s : ℝ) (hs : 0 < s)
    (f : ℝ → ℝ) (hf : aux_bounded f) :
    0 ≤ ∫ u : EuclideanSpace ℝ (Fin 2),
      f (u 0) * f (u 1) * aux_integralFctKernelAtScale s (fun x => psi x) u := by
  rcases hf with ⟨hfmeas, hfbounded⟩
  rcases hfbounded.exists_norm_le with ⟨C, hC⟩
  have hC' : ∀ x : ℝ, |f x| ≤ C := by
    intro x
    simpa [Real.norm_eq_abs] using hC (f x) ⟨x, rfl⟩
  let μ : Measure ℝ := volume.restrict (Set.Icc 1 2)
  let A : ℝ × ℝ → ℝ := fun tx =>
    f tx.2 * aux_bf_realRescaled (s * tx.1) (fun x => psi x) tx.2
  let H : ℝ × (ℝ × ℝ) → ℝ := fun q =>
    A (q.1, q.2.1) * A (q.1, q.2.2) * q.1⁻¹
  have hH : Integrable H (μ.prod volume) := by
    simpa [μ, H, A] using aux_integralFct_triple_integrable psi s hs f hfmeas C hC'
  have hHnonneg : 0 ≤ ∫ q : ℝ × (ℝ × ℝ), H q ∂(μ.prod volume) := by
    simpa [μ, H] using aux_integralFct_triple_nonnegative A (by simpa [μ, H] using hH)
  let e : EuclideanSpace ℝ (Fin 2) ≃ᵐ (ℝ × ℝ) :=
    (MeasurableEquiv.toLp 2 (Fin 2 → ℝ)).symm.trans MeasurableEquiv.finTwoArrow
  have he : MeasurePreserving e volume volume :=
    (PiLp.volume_preserving_toLp (Fin 2)).symm.trans
      (MeasureTheory.volume_preserving_finTwoArrow ℝ)
  have heprod : MeasurePreserving (Prod.map id e) (μ.prod volume) (μ.prod volume) :=
    (MeasurePreserving.id μ).prod he
  let HE : ℝ × EuclideanSpace ℝ (Fin 2) → ℝ := fun q =>
    A (q.1, q.2 0) * A (q.1, q.2 1) * q.1⁻¹
  have hHE_eq : HE = H ∘ Prod.map id e := by
    funext q
    dsimp [HE, H, e]
    simp [MeasurableEquiv.finTwoArrow_apply]
  have hHE : Integrable HE (μ.prod volume) := by
    rw [hHE_eq]
    exact (heprod.integrable_comp hH.aestronglyMeasurable).2 hH
  have hinner (t : ℝ) :
      (∫ u : EuclideanSpace ℝ (Fin 2), HE (t, u)) =
        ∫ xy : ℝ × ℝ, H (t, xy) := by
    change (∫ u : EuclideanSpace ℝ (Fin 2), H (t, e u)) =
      ∫ xy : ℝ × ℝ, H (t, xy)
    exact he.integral_comp e.measurableEmbedding (fun xy : ℝ × ℝ => H (t, xy))
  have hform :
      (∫ u : EuclideanSpace ℝ (Fin 2),
        f (u 0) * f (u 1) * aux_integralFctKernelAtScale s (fun x => psi x) u) =
        ∫ u : EuclideanSpace ℝ (Fin 2), ∫ t : ℝ, HE (t, u) ∂μ := by
    apply integral_congr_ae
    filter_upwards [] with u
    rw [show aux_integralFctKernelAtScale s (fun x => psi x) u =
        ∫ t : ℝ in Set.Icc 1 2,
          aux_bf_realRescaled (s * t) (fun x => psi x) (u 0) *
            aux_bf_realRescaled (s * t) (fun x => psi x) (u 1) * t⁻¹ by
          exact aux_integralFctKernelAtScale_eq s hs.ne' _ u]
    rw [← integral_const_mul]
    apply integral_congr_ae
    filter_upwards [] with t
    dsimp [HE, A]
    ring
  rw [hform, ← integral_integral_swap hHE]
  calc
    0 ≤ ∫ q : ℝ × (ℝ × ℝ), H q ∂(μ.prod volume) := hHnonneg
    _ = ∫ t : ℝ, ∫ xy : ℝ × ℝ, H (t, xy) ∂volume ∂μ :=
      integral_prod _ hH
    _ = ∫ t : ℝ, ∫ u : EuclideanSpace ℝ (Fin 2), HE (t, u) ∂volume ∂μ := by
      apply integral_congr_ae
      filter_upwards [] with t
      exact (hinner t).symm

/--
Integrability of the complex scale-integrated tensor used to exchange the
Fourier and scale integrals in `integralFct` (Lemma
`Auto.integralFct`).
-/
theorem aux_integralFctKernelAtScale_triple_integrable
    (psi : SchwartzMap ℝ ℝ) (s : ℝ) (hs : 0 < s) :
    Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) =>
      (aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 0) *
        aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 1) * q.1⁻¹ : ℂ))
      ((volume.restrict (Set.Icc 1 2)).prod volume) := by
  let μ : Measure ℝ := volume.restrict (Set.Icc 1 2)
  let H : ℝ × (ℝ × ℝ) → ℝ := fun q =>
    aux_bf_realRescaled (s * q.1) (fun x => psi x) q.2.1 *
      aux_bf_realRescaled (s * q.1) (fun x => psi x) q.2.2 * q.1⁻¹
  have hH : Integrable H (μ.prod volume) := by
    simpa [μ, H] using
      aux_integralFct_triple_integrable psi s hs (fun _ : ℝ => 1) (by fun_prop) 1
        (by intro x; norm_num)
  let e : EuclideanSpace ℝ (Fin 2) ≃ᵐ (ℝ × ℝ) :=
    (MeasurableEquiv.toLp 2 (Fin 2 → ℝ)).symm.trans MeasurableEquiv.finTwoArrow
  have he : MeasurePreserving e volume volume :=
    (PiLp.volume_preserving_toLp (Fin 2)).symm.trans
      (MeasureTheory.volume_preserving_finTwoArrow ℝ)
  have heprod : MeasurePreserving (Prod.map id e) (μ.prod volume) (μ.prod volume) :=
    (MeasurePreserving.id μ).prod he
  let HE : ℝ × EuclideanSpace ℝ (Fin 2) → ℝ := fun q =>
    aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 0) *
      aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 1) * q.1⁻¹
  have hHE_eq : HE = H ∘ Prod.map id e := by
    funext q
    dsimp [HE, H, e]
    simp [MeasurableEquiv.finTwoArrow_apply]
  have hHE : Integrable HE (μ.prod volume) := by
    rw [hHE_eq]
    exact (heprod.integrable_comp hH.aestronglyMeasurable).2 hH
  have hHEC : Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) => (HE q : ℂ))
      (μ.prod volume) := hHE.ofReal
  simpa [μ, HE] using hHEC

/--
Joint integrability of the scale parameter and spatial variables for the
expanded `integralFctKernel` at a positive scale.  This is the Fubini input for
parameterized Brascamp--Lieb forms.
-/
theorem integralFctKernelAtScale_triple_integrable
    (psi : SchwartzMap ℝ ℝ) (s : ℝ) (hs : 0 < s) :
    Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) =>
      (aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 0) *
        aux_bf_realRescaled (s * q.1) (fun x => psi x) (q.2 1) * q.1⁻¹ : ℂ))
      ((volume.restrict (Set.Icc 1 2)).prod volume) :=
  aux_integralFctKernelAtScale_triple_integrable psi s hs

/--
Multiplication by a scalar commutes with the Fourier integral.  This
form is used for the `dt/t` factor in `integralFct`.
-/
theorem aux_fourier_mul_const
    {V} [NormedAddCommGroup V] [InnerProductSpace ℝ V]
    [MeasurableSpace V] [BorelSpace V] [FiniteDimensional ℝ V]
    (f : V → ℂ) (c : ℂ) (xi : V) :
    FourierTransform.fourier (fun u => f u * c) xi =
      FourierTransform.fourier f xi * c := by
  simp_rw [Real.fourier_eq']
  rw [← integral_mul_const]
  apply integral_congr_ae
  filter_upwards [] with u
  simp [smul_eq_mul, mul_assoc]

/-! ### Schwartz packaging of the scale-integrated kernel

The physical kernel is defined by an ordinary compact parameter integral.  For
the later Whitney arguments it is useful to have the same function bundled as a
Schwartz map.  We first package its compactly supported Fourier-side profile,
then invert the Schwartz Fourier transform. -/

noncomputable def aux_integralFctFourierKernel (psi : SchwartzMap ℝ ℝ) :
    EuclideanSpace ℝ (Fin 2) → ℂ :=
  fun xi => ∫ t : ℝ in Icc (1 : ℝ) 2,
    FourierTransform.fourier (fun x : ℝ => (psi x : ℂ)) (t * xi 0) *
      FourierTransform.fourier (fun x : ℝ => (psi x : ℂ)) (t * xi 1) *
        ((t⁻¹ : ℝ) : ℂ)

theorem aux_integralFctFourierKernel_smooth (psi : SchwartzMap ℝ ℝ) :
    ContDiff ℝ (⊤ : ℕ∞) (aux_integralFctFourierKernel psi) := by
  let q : ℝ → ℂ := FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))
  have hq : ContDiff ℝ (⊤ : ℕ∞) q := by
    let psiC : SchwartzMap ℝ ℂ :=
      SchwartzMap.postcompCLM Complex.ofRealCLM psi
    have hs : ContDiff ℝ (⊤ : ℕ∞) (FourierTransform.fourier psiC : ℝ → ℂ) :=
      (FourierTransform.fourier psiC).smooth _
    have hpsiC : (psiC : ℝ → ℂ) = fun x : ℝ => (psi x : ℂ) := by
      funext x
      simp [psiC, SchwartzMap.postcompCLM_apply]
    rw [SchwartzMap.fourier_coe, hpsiC] at hs
    exact hs
  have hjoint : ContDiffOn ℝ (⊤ : ℕ∞)
      (fun p : EuclideanSpace ℝ (Fin 2) × ℝ =>
        q (p.2 * p.1 0) * q (p.2 * p.1 1) * ((p.2⁻¹ : ℝ) : ℂ))
      (univ ×ˢ Ioi (0 : ℝ)) := by
    have hne : ∀ p ∈ (univ : Set (EuclideanSpace ℝ (Fin 2))) ×ˢ Ioi (0 : ℝ),
        p.2 ≠ 0 := by
      rintro ⟨u, t⟩ ⟨-, ht⟩
      exact ne_of_gt ht
    have hcoord0 : ContDiffOn ℝ (⊤ : ℕ∞)
        (fun p : EuclideanSpace ℝ (Fin 2) × ℝ => p.2 * p.1 0)
        (univ ×ˢ Ioi (0 : ℝ)) := by fun_prop
    have hcoord1 : ContDiffOn ℝ (⊤ : ℕ∞)
        (fun p : EuclideanSpace ℝ (Fin 2) × ℝ => p.2 * p.1 1)
        (univ ×ˢ Ioi (0 : ℝ)) := by fun_prop
    have hinvR : ContDiffOn ℝ (⊤ : ℕ∞)
        (fun p : EuclideanSpace ℝ (Fin 2) × ℝ => p.2⁻¹)
        (univ ×ˢ Ioi (0 : ℝ)) := by
      fun_prop
    have hinvC : ContDiffOn ℝ (⊤ : ℕ∞)
        (fun p : EuclideanSpace ℝ (Fin 2) × ℝ => ((p.2⁻¹ : ℝ) : ℂ))
        (univ ×ˢ Ioi (0 : ℝ)) :=
      Complex.ofRealCLM.contDiff.comp_contDiffOn hinvR
    exact ((hq.comp_contDiffOn hcoord0).mul (hq.comp_contDiffOn hcoord1)).mul hinvC
  change ContDiff ℝ (⊤ : ℕ∞)
    (fun xi : EuclideanSpace ℝ (Fin 2) => ∫ t : ℝ in Icc (1 : ℝ) 2,
      q (t * xi 0) * q (t * xi 1) * ((t⁻¹ : ℝ) : ℂ))
  exact aux_contDiff_infty_setIntegral_Icc_of_contDiffOn _ hjoint

noncomputable def aux_integralFctFourierKernelPlaneEquiv :
    EuclideanSpace ℝ (Fin 2) ≃L[ℝ] (ℝ × ℝ) :=
  (EuclideanSpace.equiv (Fin 2) ℝ).trans
    (ContinuousLinearEquiv.finTwoArrow ℝ ℝ)

theorem aux_integralFctFourierKernelPlaneEquiv_apply
    (u : EuclideanSpace ℝ (Fin 2)) :
    aux_integralFctFourierKernelPlaneEquiv u = (u 0, u 1) := by
  simp [aux_integralFctFourierKernelPlaneEquiv]

theorem aux_integralFctFourierKernel_compact (psi : SchwartzMap ℝ ℝ)
    (hsupp : Function.support
      (FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))) ⊆
        aux_annulusOne 1 ((2 : ℝ) ^ 2)) :
    HasCompactSupport (aux_integralFctFourierKernel psi) := by
  let K : Set (EuclideanSpace ℝ (Fin 2)) :=
    aux_integralFctFourierKernelPlaneEquiv ⁻¹'
      (Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2) ×ˢ
        Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2))
  have hinterval : IsCompact (Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2)) := isCompact_Icc
  have hK : IsCompact K := by
    exact (aux_integralFctFourierKernelPlaneEquiv.toHomeomorph.isCompact_preimage).mpr
      (hinterval.prod hinterval)
  have hcoord_zero (x : ℝ) (hx : x ∉ Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2))
      (t : ℝ) (ht : t ∈ Icc (1 : ℝ) 2) :
      FourierTransform.fourier (fun y : ℝ => (psi y : ℂ)) (t * x) = 0 := by
    apply Function.notMem_support.mp
    intro hmem
    apply hx
    have hmem' := hsupp hmem
    unfold aux_annulusOne at hmem'
    have htpos : 0 < t := lt_of_lt_of_le zero_lt_one ht.1
    have htx : |t * x| ≤ (2 : ℝ) ^ 2 := by
      simpa using hmem'.2
    have hxabs : |x| ≤ (2 : ℝ) ^ 2 := by
      calc
        |x| = 1 * |x| := by ring
        _ ≤ t * |x| := mul_le_mul_of_nonneg_right ht.1 (abs_nonneg x)
        _ = |t * x| := by rw [abs_mul, abs_of_pos htpos]
        _ ≤ (2 : ℝ) ^ 2 := htx
    exact abs_le.mp hxabs
  apply HasCompactSupport.intro hK
  intro u hu
  have hu' : ¬ (u 0 ∈ Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2) ∧
      u 1 ∈ Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2)) := by
    intro huu
    apply hu
    change aux_integralFctFourierKernelPlaneEquiv u ∈
      (Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2) ×ˢ
        Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2))
    rw [aux_integralFctFourierKernelPlaneEquiv_apply]
    exact huu
  unfold aux_integralFctFourierKernel
  by_cases h0 : u 0 ∈ Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2)
  · have h1 : u 1 ∉ Icc (-((2 : ℝ) ^ 2)) ((2 : ℝ) ^ 2) := fun h1 => hu' ⟨h0, h1⟩
    apply integral_eq_zero_of_ae
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
    rw [hcoord_zero (u 1) h1 t ht]
    simp
  · apply integral_eq_zero_of_ae
    filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
    rw [hcoord_zero (u 0) h0 t ht]
    simp

noncomputable def aux_integralFctFourierKernelSchwartz (psi : SchwartzMap ℝ ℝ)
    (hsupp : Function.support
      (FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))) ⊆
        aux_annulusOne 1 ((2 : ℝ) ^ 2)) :
    SchwartzMap (EuclideanSpace ℝ (Fin 2)) ℂ :=
  (aux_integralFctFourierKernel_compact psi hsupp).toSchwartzMap
    (aux_integralFctFourierKernel_smooth psi)

theorem aux_integralFctFourierKernelSchwartz_apply (psi : SchwartzMap ℝ ℝ)
    (hsupp : Function.support
      (FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))) ⊆
        aux_annulusOne 1 ((2 : ℝ) ^ 2))
    (u : EuclideanSpace ℝ (Fin 2)) :
    aux_integralFctFourierKernelSchwartz psi hsupp u =
      aux_integralFctFourierKernel psi u := rfl

theorem aux_integralFctKernel_continuous (psi : SchwartzMap ℝ ℝ) :
    Continuous (fun u : EuclideanSpace ℝ (Fin 2) =>
      (integralFctKernel (fun x => psi x) u : ℂ)) := by
  let F : EuclideanSpace ℝ (Fin 2) → ℝ → ℝ := fun u t =>
    aux_bf_realRescaled t (fun x => psi x) (u 0) *
      aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹
  have hF : ContDiffOn ℝ (⊤ : ℕ∞) F.uncurry
      (univ ×ˢ Ioi (0 : ℝ)) := by
    dsimp [F, aux_bf_realRescaled]
    have hne : ∀ p ∈ (univ : Set (EuclideanSpace ℝ (Fin 2))) ×ˢ Ioi (0 : ℝ),
        p.2 ≠ 0 := by
      rintro ⟨u, t⟩ ⟨-, ht⟩
      exact ne_of_gt ht
    fun_prop
  have hcontR : Continuous (fun u : EuclideanSpace ℝ (Fin 2) =>
      ∫ t : ℝ in Icc (1 : ℝ) 2, F u t) :=
    (aux_contDiff_infty_setIntegral_Icc_of_contDiffOn F hF).continuous
  have heq : (fun u : EuclideanSpace ℝ (Fin 2) =>
      integralFctKernel (fun x => psi x) u) =
      fun u => ∫ t : ℝ in Icc (1 : ℝ) 2, F u t := by
    funext u
    rfl
  exact Complex.ofRealCLM.continuous.comp (by simpa [heq] using hcontR)

theorem aux_integralFctKernel_integrable (psi : SchwartzMap ℝ ℝ) :
    Integrable (fun u : EuclideanSpace ℝ (Fin 2) =>
      (integralFctKernel (fun x => psi x) u : ℂ)) := by
  let k : ℝ → EuclideanSpace ℝ (Fin 2) → ℂ := fun t u =>
    (aux_bf_realRescaled t (fun x => psi x) (u 0) *
      aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹ : ℂ)
  have hk : Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) => k q.1 q.2)
      ((volume.restrict (Icc (1 : ℝ) 2)).prod volume) := by
    simpa [k] using aux_integralFctKernelAtScale_triple_integrable psi 1 (by norm_num)
  have hkernel :
      (fun u : EuclideanSpace ℝ (Fin 2) =>
        (integralFctKernel (fun x => psi x) u : ℂ)) =
        fun u => ∫ t : ℝ in Icc (1 : ℝ) 2, k t u := by
    funext u
    change (↑(∫ t : ℝ in Icc (1 : ℝ) 2,
      aux_bf_realRescaled t (fun x => psi x) (u 0) *
        aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹) : ℂ) = _
    simpa [k] using
      (integral_ofReal (𝕜 := ℂ) (μ := volume.restrict (Icc (1 : ℝ) 2))
        (f := fun t : ℝ =>
          aux_bf_realRescaled t (fun x => psi x) (u 0) *
            aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹)).symm
  rw [hkernel]
  exact hk.integral_prod_right

theorem aux_integralFctKernel_fourier_eq (psi : SchwartzMap ℝ ℝ) :
    FourierTransform.fourier
      (fun u : EuclideanSpace ℝ (Fin 2) =>
        (integralFctKernel (fun x => psi x) u : ℂ)) =
      aux_integralFctFourierKernel psi := by
  let k : ℝ → EuclideanSpace ℝ (Fin 2) → ℂ := fun t u =>
    (aux_bf_realRescaled t (fun x => psi x) (u 0) *
      aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹ : ℂ)
  have hk : Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) => k q.1 q.2)
      ((volume.restrict (Icc (1 : ℝ) 2)).prod volume) := by
    simpa [k] using aux_integralFctKernelAtScale_triple_integrable psi 1 (by norm_num)
  have hkernel :
      (fun u : EuclideanSpace ℝ (Fin 2) =>
        (integralFctKernel (fun x => psi x) u : ℂ)) =
        fun u => ∫ t : ℝ in Icc (1 : ℝ) 2, k t u := by
    funext u
    change (↑(∫ t : ℝ in Icc (1 : ℝ) 2,
      aux_bf_realRescaled t (fun x => psi x) (u 0) *
        aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹) : ℂ) = _
    simpa [k] using
      (integral_ofReal (𝕜 := ℂ) (μ := volume.restrict (Icc (1 : ℝ) 2))
        (f := fun t : ℝ =>
          aux_bf_realRescaled t (fun x => psi x) (u 0) *
            aux_bf_realRescaled t (fun x => psi x) (u 1) * t⁻¹)).symm
  funext xi
  rw [hkernel, aux_fourier_setIntegral_swap_of_integrable k 1 2 xi hk]
  apply integral_congr_ae
  filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
  have htpos : 0 < t := lt_of_lt_of_le zero_lt_one ht.1
  have hkt : k t = fun u =>
      (aux_bf_realRescaled t (fun x => psi x) (u 0) : ℂ) *
        (aux_bf_realRescaled t (fun x => psi x) (u 1) : ℂ) * (t⁻¹ : ℂ) := by
    funext u
    dsimp [k]
    push_cast
    ring
  rw [hkt, aux_fourier_mul_const, aux_fourier_tensor_two,
    aux_realRescaled_fourier t htpos, aux_realRescaled_fourier t htpos]
  rw [Complex.ofReal_inv]

/--
The Fourier transform of the compact scale-integrated tensor kernel.
This explicit form makes the cancellation on the diagonal available to the
short-variation estimates.
-/
theorem integralFctKernel_fourier_eq (psi : SchwartzMap ℝ ℝ) :
    FourierTransform.fourier
      (fun u : EuclideanSpace ℝ (Fin 2) =>
        (integralFctKernel (fun x => psi x) u : ℂ)) =
      fun xi => ∫ t : ℝ in Icc (1 : ℝ) 2,
        FourierTransform.fourier (fun x : ℝ => (psi x : ℂ)) (t * xi 0) *
          FourierTransform.fourier (fun x : ℝ => (psi x : ℂ)) (t * xi 1) *
            ((t⁻¹ : ℝ) : ℂ) := by
  exact aux_integralFctKernel_fourier_eq psi

/--
A Schwartz realization of the compact scale-integrated tensor kernel.
Its Fourier-side construction is identified with `integralFctKernel` by
`integralFctKernelSchwartz_apply`.
-/
noncomputable def integralFctKernelSchwartz (psi : SchwartzMap ℝ ℝ)
    (hsupp : Function.support
      (FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))) ⊆
        aux_annulusOne 1 ((2 : ℝ) ^ 2)) :
    SchwartzMap (EuclideanSpace ℝ (Fin 2)) ℝ :=
  SchwartzMap.postcompCLM Complex.reCLM
    (FourierTransform.fourierInv (aux_integralFctFourierKernelSchwartz psi hsupp))

/--
The coercion of `integralFctKernelSchwartz` is the original physical
kernel.
-/
theorem integralFctKernelSchwartz_apply (psi : SchwartzMap ℝ ℝ)
    (hsupp : Function.support
      (FourierTransform.fourier (fun x : ℝ => (psi x : ℂ))) ⊆
        aux_annulusOne 1 ((2 : ℝ) ^ 2))
    (u : EuclideanSpace ℝ (Fin 2)) :
    integralFctKernelSchwartz psi hsupp u = integralFctKernel (fun x => psi x) u := by
  let f : EuclideanSpace ℝ (Fin 2) → ℂ := fun u =>
    (integralFctKernel (fun x => psi x) u : ℂ)
  let H : SchwartzMap (EuclideanSpace ℝ (Fin 2)) ℂ :=
    aux_integralFctFourierKernelSchwartz psi hsupp
  have hH : (H : EuclideanSpace ℝ (Fin 2) → ℂ) = FourierTransform.fourier f := by
    funext xi
    exact (aux_integralFctKernel_fourier_eq psi).symm ▸
      (aux_integralFctFourierKernelSchwartz_apply psi hsupp xi)
  have hhatint : Integrable (FourierTransform.fourier f) := by
    rw [← hH]
    exact H.integrable
  have hinv := (aux_integralFctKernel_continuous psi).fourierInv_fourier_eq
    (aux_integralFctKernel_integrable psi) hhatint
  have hcomplex : FourierTransform.fourierInv H u = f u := by
    rw [SchwartzMap.fourierInv_coe, hH]
    exact congrFun hinv u
  rw [integralFctKernelSchwartz, SchwartzMap.postcompCLM_apply]
  simpa [f] using congrArg Complex.re hcomplex

/--
The Fourier-support inclusion in the first part of the conclusion of
`integralFct` (Lemma `Auto.integralFct`).
-/
theorem aux_integralFct_fourier_support
    (psi : SchwartzMap ℝ ℝ)
    (hpsi : Function.support (FourierTransform.fourier (fun x : ℝ ↦ (psi x : ℂ))) ⊆
      Set.Icc (-1 : ℝ) (-(1 / 4 : ℝ)) ∪ Set.Icc (1 / 4 : ℝ) 1)
    (ell : ℤ) :
    Function.support (FourierTransform.fourier
      (fun u : EuclideanSpace ℝ (Fin 2) ↦
        (aux_integralFctKernelAtScale ((2 : ℝ) ^ ell) (fun x ↦ psi x) u : ℂ))) ⊆
      aux_productSet (aux_integralFctBand ell) := by
  intro xi hxi
  by_contra hx
  apply Function.mem_support.mp hxi
  let s : ℝ := (2 : ℝ) ^ ell
  have hs : 0 < s := zpow_pos (by norm_num) _
  let k : ℝ → EuclideanSpace ℝ (Fin 2) → ℂ := fun t u =>
    (aux_bf_realRescaled (s * t) (fun x => psi x) (u 0) *
      aux_bf_realRescaled (s * t) (fun x => psi x) (u 1) * t⁻¹ : ℂ)
  have hk : Integrable (fun q : ℝ × EuclideanSpace ℝ (Fin 2) => k q.1 q.2)
      ((volume.restrict (Set.Icc 1 2)).prod volume) := by
    simpa [s, k] using aux_integralFctKernelAtScale_triple_integrable psi s hs
  have hkernel :
      (fun u : EuclideanSpace ℝ (Fin 2) =>
        (aux_integralFctKernelAtScale s (fun x => psi x) u : ℂ)) =
        fun u => ∫ t : ℝ in Set.Icc 1 2, k t u := by
    funext u
    rw [aux_integralFctKernelAtScale_eq s hs.ne' _ u]
    simpa [k] using
      (integral_ofReal (𝕜 := ℂ) (μ := volume.restrict (Set.Icc (1 : ℝ) 2))
        (f := fun t : ℝ =>
          aux_bf_realRescaled (s * t) (fun x => psi x) (u 0) *
            aux_bf_realRescaled (s * t) (fun x => psi x) (u 1) * t⁻¹)).symm
  rw [show ((2 : ℝ) ^ ell) = s by rfl, hkernel]
  rw [aux_fourier_setIntegral_swap_of_integrable k 1 2 xi hk]
  apply integral_eq_zero_of_ae
  filter_upwards [ae_restrict_mem measurableSet_Icc] with t ht
  simp only [aux_productSet, Set.mem_ofPred_eq] at hx
  rcases not_and_or.mp hx with hx0 | hx1
  · have hst : 0 < s * t := mul_pos hs (lt_of_lt_of_le zero_lt_one ht.1)
    have hk_t : k t = fun u =>
        (aux_bf_realRescaled (s * t) (fun x => psi x) (u 0) : ℂ) *
          (aux_bf_realRescaled (s * t) (fun x => psi x) (u 1) : ℂ) * (t⁻¹ : ℂ) := by
      funext u
      dsimp [k]
      push_cast
      ring
    rw [hk_t, aux_fourier_mul_const,
      aux_fourier_tensor_two, aux_realRescaled_fourier (s * t) hst,
      aux_realRescaled_fourier (s * t) hst]
    rw [aux_integralFct_fourier_zero_outside_band psi hpsi ell t ht (xi 0) hx0]
    simp
  · have hst : 0 < s * t := mul_pos hs (lt_of_lt_of_le zero_lt_one ht.1)
    have hk_t : k t = fun u =>
        (aux_bf_realRescaled (s * t) (fun x => psi x) (u 0) : ℂ) *
          (aux_bf_realRescaled (s * t) (fun x => psi x) (u 1) : ℂ) * (t⁻¹ : ℂ) := by
      funext u
      dsimp [k]
      push_cast
      ring
    rw [hk_t, aux_fourier_mul_const,
      aux_fourier_tensor_two, aux_realRescaled_fourier (s * t) hst,
      aux_realRescaled_fourier (s * t) hst]
    rw [aux_integralFct_fourier_zero_outside_band psi hpsi ell t ht (xi 1) hx1]
    simp

/--
**Lemma.**

Let $\psi:\mathbb{R}\to \mathbb{R}$ be a Schwartz function and assume that

$$
              \textup{supp}(\widehat{\psi})
\subset  [-1,-2^{-2}]\cup [2^{-2},1]
$$

Let $\Psi:\mathbb{R}^2\to \mathbb{R}$ be defined as

$$
\Psi(u,v) = \int_1^2 \psi_{(t)}(u) \psi_{(t)}(v) \tfrac{dt}{t}
$$

and let $\ell\in\mathbb{Z}$.
   Then

1. For all $(u,v)\in \mathbb{R}^2$,  $\Psi_{(2^\ell)}(u,v) = \Psi_{(2^\ell)}(v,u)$

1. For all bounded functions $f:\mathbb{R}\to\mathbb{R}$,

   $$
   \int_{\mathbb{R}^2} f(u){f(v)} \Psi_{(2^\ell)}(u,v)\,dudv
   \ge 0
   $$

1. $         \textup{supp}(\widehat{\Psi_{(2^\ell)}})
\subset  ([-2^{-\ell},-2^{-3-\ell}]\cup [2^{-3-\ell},2^{-\ell}])^2 \subset
   \textup{Ann}_1(2^{-\ell},2^3)^2$
-/
theorem integralFct (psi : SchwartzMap ℝ ℝ)
    (hpsi : Function.support
      (FourierTransform.fourier (fun x : ℝ ↦ (psi x : ℂ))) ⊆
        Set.Icc (-1 : ℝ) (-(1 / 4 : ℝ)) ∪ Set.Icc (1 / 4 : ℝ) 1)
    (ell : ℤ) :
    (∀ u : EuclideanSpace ℝ (Fin 2),
      aux_integralFctKernelAtScale ((2 : ℝ) ^ ell) (fun x ↦ psi x) u =
        aux_integralFctKernelAtScale ((2 : ℝ) ^ ell) (fun x ↦ psi x)
          (aux_swapTwo u)) ∧
    (∀ f : ℝ → ℝ, aux_bounded f →
      0 ≤ ∫ u : EuclideanSpace ℝ (Fin 2),
        f (u 0) * f (u 1) *
          aux_integralFctKernelAtScale ((2 : ℝ) ^ ell) (fun x ↦ psi x) u) ∧
    (Function.support (FourierTransform.fourier
      (fun u : EuclideanSpace ℝ (Fin 2) ↦
        (aux_integralFctKernelAtScale ((2 : ℝ) ^ ell) (fun x ↦ psi x) u : ℂ))) ⊆
        aux_productSet (aux_integralFctBand ell) ∧
      aux_productSet (aux_integralFctBand ell) ⊆
        aux_productSet (aux_annulusOne ((2 : ℝ) ^ (-ell)) ((2 : ℝ) ^ 3))) := by
  have hs : 0 < (2 : ℝ) ^ ell := zpow_pos (by norm_num) _
  refine ⟨?_, ?_, ?_⟩
  · intro u
    unfold aux_integralFctKernelAtScale rescaled integralFctKernel aux_swapTwo
    congr 1
    apply integral_congr_ae
    filter_upwards [] with t
    simp only [Fin.isValue, PiLp.smul_apply, smul_eq_mul, Matrix.cons_val_zero,
      Matrix.cons_val_one, Matrix.cons_val_fin_one, mul_eq_mul_right_iff, inv_eq_zero]
    exact Or.inl (mul_comm _ _)
  · intro f hf
    exact aux_integralFctKernelAtScale_nonnegative psi ((2 : ℝ) ^ ell) hs f hf
  · refine ⟨aux_integralFct_fourier_support psi hpsi ell, ?_⟩
    intro xi hxi
    rcases hxi with ⟨hx0, hx1⟩
    let r : ℝ := (2 : ℝ) ^ (-ell)
    have hr : 0 ≤ r := (zpow_pos (by norm_num) _).le
    have hpow3 : (2 : ℝ) ^ (-3 - ell) = r / 8 := by
      dsimp [r]
      rw [show (-3 - ell : ℤ) = (-3 : ℤ) + (-ell) by omega,
        zpow_add₀ (by norm_num : (2 : ℝ) ≠ 0), zpow_neg]
      norm_num
      ring
    have hR : ((2 : ℝ) ^ 3) = 8 := by norm_num
    have hband : aux_integralFctBand ell ⊆
        aux_annulusOne ((2 : ℝ) ^ (-ell)) ((2 : ℝ) ^ 3) := by
      rw [show aux_integralFctBand ell = Set.Icc (-r) (-(r / 8)) ∪ Set.Icc (r / 8) r by
            dsimp [aux_integralFctBand, r]
            rw [hpow3],
          show aux_annulusOne ((2 : ℝ) ^ (-ell)) ((2 : ℝ) ^ 3) =
            {x : ℝ | r / 8 ≤ |x| ∧ |x| ≤ 8 * r} by
            dsimp [aux_annulusOne, r]
            rw [hR]]
      exact aux_band_subset_annulus r hr
    exact ⟨hband hx0, hband hx1⟩

/--
**Lemma.**

Let
$\Psi:\mathbb{R}^2\to \mathbb{R}$ be such   that $\Psi(u_0,u_1)=\Psi(u_1,u_0)$ for all $(u_0,u_1)\in
\mathbb{R}^2$ and such that
for all bounded functions $g:\mathbb{R}\to\mathbb{R}$,

$$
    \int_{\mathbb{R}^2} g(u_0){g(u_1)} \Psi(u)\,du \ge 0
$$

Then for all $\xi\in \mathbb{R}$,
$$
\widehat{\Psi}(\xi,-\xi)\geq 0.
$$
-/
theorem phiPosV2 (Psi : EuclideanSpace ℝ (Fin 2) → ℝ)
    (hsym : ∀ u : EuclideanSpace ℝ (Fin 2), Psi u = Psi (aux_swapTwo u))
    (hpos : ∀ g : ℝ → ℝ, aux_bounded g →
      0 ≤ ∫ u : EuclideanSpace ℝ (Fin 2), g (u 0) * g (u 1) * Psi u)
    (xi : ℝ) :
    0 ≤ (FourierTransform.fourier (fun u : EuclideanSpace ℝ (Fin 2) ↦ (Psi u : ℂ))
      (WithLp.toLp 2 ![xi, -xi])).re := by
  have _hsym := hsym
  have hinter (u : EuclideanSpace ℝ (Fin 2)) :
      inner ℝ u (WithLp.toLp 2 ![xi, -xi]) = xi * (u 0 - u 1) := by
    change inner ℝ (WithLp.toLp 2 u.ofLp) (WithLp.toLp 2 ![xi, -xi]) = _
    rw [EuclideanSpace.inner_toLp_toLp]
    simp [dotProduct, Fin.sum_univ_two]
    ring
  let c : ℝ → ℝ := fun x => Real.cos (2 * Real.pi * xi * x)
  let s : ℝ → ℝ := fun x => Real.sin (2 * Real.pi * xi * x)
  have hcbounded : aux_bounded c := by
    constructor
    · dsimp [c]
      fun_prop
    · apply (Metric.isBounded_Icc (-1) 1).subset
      rintro _ ⟨x, rfl⟩
      exact abs_le.mp (Real.abs_cos_le_one _)
  have hsbounded : aux_bounded s := by
    constructor
    · dsimp [s]
      fun_prop
    · apply (Metric.isBounded_Icc (-1) 1).subset
      rintro _ ⟨x, rfl⟩
      exact abs_le.mp (Real.abs_sin_le_one _)
  have hcpos := hpos c hcbounded
  have hspos := hpos s hsbounded
  by_cases hPsi : Integrable Psi
  · have hPsiC : Integrable (fun u : EuclideanSpace ℝ (Fin 2) => (Psi u : ℂ)) := hPsi.ofReal
    have hphase : Integrable (fun u : EuclideanSpace ℝ (Fin 2) =>
        𝐞 (-inner ℝ u (WithLp.toLp 2 ![xi, -xi])) • (Psi u : ℂ)) := by
      rw [Real.fourierIntegral_convergent_iff]
      exact hPsiC
    have hcint : Integrable (fun u : EuclideanSpace ℝ (Fin 2) => c (u 0) * c (u 1) * Psi u) := by
      apply hPsi.bdd_mul
      · fun_prop
      · filter_upwards [] with u
        change |c (u 0) * c (u 1)| ≤ 1
        rw [abs_mul]
        simpa [c] using mul_le_one₀ (Real.abs_cos_le_one _) (abs_nonneg _)
          (Real.abs_cos_le_one _)
    have hsint : Integrable (fun u : EuclideanSpace ℝ (Fin 2) => s (u 0) * s (u 1) * Psi u) := by
      apply hPsi.bdd_mul
      · fun_prop
      · filter_upwards [] with u
        change |s (u 0) * s (u 1)| ≤ 1
        rw [abs_mul]
        simpa [s] using mul_le_one₀ (Real.abs_sin_le_one _) (abs_nonneg _)
          (Real.abs_sin_le_one _)
    rw [Real.fourier_eq]
    change 0 ≤ RCLike.re (∫ u : EuclideanSpace ℝ (Fin 2),
      𝐞 (-inner ℝ u (WithLp.toLp 2 ![xi, -xi])) • (Psi u : ℂ))
    rw [← integral_re hphase]
    calc
      0 ≤ (∫ u : EuclideanSpace ℝ (Fin 2), c (u 0) * c (u 1) * Psi u) +
          ∫ u : EuclideanSpace ℝ (Fin 2), s (u 0) * s (u 1) * Psi u :=
        add_nonneg hcpos hspos
      _ = ∫ u : EuclideanSpace ℝ (Fin 2),
          c (u 0) * c (u 1) * Psi u + s (u 0) * s (u 1) * Psi u := by
        rw [integral_add hcint hsint]
      _ = ∫ u : EuclideanSpace ℝ (Fin 2),
          RCLike.re (𝐞 (-inner ℝ u (WithLp.toLp 2 ![xi, -xi])) • (Psi u : ℂ)) := by
        apply integral_congr_ae
        filter_upwards [] with u
        have hcos : Real.cos (2 * Real.pi * (-inner ℝ u (WithLp.toLp 2 ![xi, -xi]))) =
            c (u 0) * c (u 1) + s (u 0) * s (u 1) := by
          rw [hinter]
          rw [show 2 * Real.pi * (-(xi * (u 0 - u 1))) =
              -(2 * Real.pi * xi * u 0 - 2 * Real.pi * xi * u 1) by ring,
            Real.cos_neg, Real.cos_sub]
        rw [Circle.smul_def, Real.fourierChar_apply]
        simp only [smul_eq_mul, RCLike.mul_re]
        change c (u 0) * c (u 1) * Psi u + s (u 0) * s (u 1) * Psi u =
          (Complex.exp ((↑(2 * Real.pi * (-inner ℝ u (WithLp.toLp 2 ![xi, -xi]))) : ℂ) *
            Complex.I)).re * Psi u -
          (Complex.exp ((↑(2 * Real.pi * (-inner ℝ u (WithLp.toLp 2 ![xi, -xi]))) : ℂ) *
            Complex.I)).im * 0
        rw [Complex.exp_ofReal_mul_I_re, mul_zero, sub_zero, hcos]
        ring
  · have hPsiC : ¬ Integrable (fun u : EuclideanSpace ℝ (Fin 2) => (Psi u : ℂ)) := by
      intro h
      apply hPsi
      simpa using h.re
    have hphase : ¬ Integrable (fun u : EuclideanSpace ℝ (Fin 2) =>
        𝐞 (-inner ℝ u (WithLp.toLp 2 ![xi, -xi])) • (Psi u : ℂ)) := by
      rw [Real.fourierIntegral_convergent_iff]
      exact hPsiC
    rw [Real.fourier_eq, integral_undef hphase]
    norm_num

/-- The coordinate swap as a linear isometry, for Fourier-symmetry arguments. -/
noncomputable def aux_swapTwoLinearIsometry :
    EuclideanSpace ℝ (Fin 2) ≃ₗᵢ[ℝ] EuclideanSpace ℝ (Fin 2) :=
  LinearIsometryEquiv.piLpCongrLeft 2 ℝ ℝ (Equiv.swap 0 1)

theorem aux_swapTwoLinearIsometry_apply (u : EuclideanSpace ℝ (Fin 2)) :
    aux_swapTwoLinearIsometry u = aux_swapTwo u := by
  ext i
  fin_cases i <;> simp [aux_swapTwoLinearIsometry, aux_swapTwo, Equiv.piCongrLeft']

/-- The Fourier transform of a real-valued function has conjugate symmetry. -/
theorem aux_fourier_conj_of_real (Psi : EuclideanSpace ℝ (Fin 2) → ℝ)
    (w : EuclideanSpace ℝ (Fin 2)) :
    FourierTransform.fourier (fun u => (Psi u : ℂ)) (-w) =
      (starRingEnd ℂ) (FourierTransform.fourier (fun u => (Psi u : ℂ)) w) := by
  rw [Real.fourier_eq, Real.fourier_eq, ← integral_conj]
  change (∫ v : EuclideanSpace ℝ (Fin 2),
      𝐞 (-inner ℝ v (-w)) • (Psi v : ℂ)) =
    ∫ v : EuclideanSpace ℝ (Fin 2),
      star (𝐞 (-inner ℝ v w) • (Psi v : ℂ))
  apply integral_congr_ae
  filter_upwards [] with u
  rw [Circle.smul_def, Circle.smul_def, Real.fourierChar_apply,
    Real.fourierChar_apply]
  change Complex.exp (↑(2 * Real.pi * (-inner ℝ u (-w))) * Complex.I) * (Psi u : ℂ) =
    (starRingEnd ℂ)
      (Complex.exp (↑(2 * Real.pi * (-inner ℝ u w)) * Complex.I) * (Psi u : ℂ))
  rw [map_mul]
  congr 1
  · rw [← Complex.exp_conj]
    rw [inner_neg_right]
    simp only [map_mul, Complex.conj_I, Complex.conj_ofReal]
    congr 1
    push_cast
    ring
  · simp

theorem aux_fourier_diagonal_even_of_swap (Psi : EuclideanSpace ℝ (Fin 2) → ℝ)
    (hsym : ∀ u, Psi u = Psi (aux_swapTwoLinearIsometry u)) (xi : ℝ) :
    FourierTransform.fourier (fun u => (Psi u : ℂ)) (WithLp.toLp 2 ![-xi, xi]) =
      FourierTransform.fourier (fun u => (Psi u : ℂ)) (WithLp.toLp 2 ![xi, -xi]) := by
  calc
    FourierTransform.fourier (fun u => (Psi u : ℂ)) (WithLp.toLp 2 ![-xi, xi]) =
        FourierTransform.fourier (fun u => (Psi u : ℂ))
          (aux_swapTwoLinearIsometry (WithLp.toLp 2 ![xi, -xi])) := by
            rw [show aux_swapTwoLinearIsometry (WithLp.toLp 2 ![xi, -xi]) =
                WithLp.toLp 2 ![-xi, xi] by
              ext i
              fin_cases i <;>
                simp [aux_swapTwoLinearIsometry, Equiv.piCongrLeft']]
    _ = FourierTransform.fourier ((fun u => (Psi u : ℂ)) ∘ aux_swapTwoLinearIsometry)
          (WithLp.toLp 2 ![xi, -xi]) := by
            exact (Real.fourier_comp_linearIsometry aux_swapTwoLinearIsometry _ _).symm
    _ = FourierTransform.fourier (fun u => (Psi u : ℂ))
          (WithLp.toLp 2 ![xi, -xi]) := by
            apply Real.fourier_congr_ae
            filter_upwards [] with u
            change (Psi (aux_swapTwoLinearIsometry u) : ℂ) = (Psi u : ℂ)
            rw [← hsym u]

/--
For a real coordinate-symmetric two-dimensional function, its Fourier transform on the
anti-diagonal is real and even.
-/
theorem fourierDiagonalRealEven (Psi : EuclideanSpace ℝ (Fin 2) → ℝ)
    (hsym : ∀ u : EuclideanSpace ℝ (Fin 2), Psi u = Psi (aux_swapTwo u)) :
    (∀ xi : ℝ, ∃ r : ℝ,
      FourierTransform.fourier (fun u => (Psi u : ℂ))
        (WithLp.toLp 2 ![xi, -xi]) = r) ∧
    ∀ xi : ℝ,
      FourierTransform.fourier (fun u => (Psi u : ℂ))
        (WithLp.toLp 2 ![-xi, xi]) =
      FourierTransform.fourier (fun u => (Psi u : ℂ))
        (WithLp.toLp 2 ![xi, -xi]) := by
  have hsym' : ∀ u, Psi u = Psi (aux_swapTwoLinearIsometry u) := by
    intro u
    rw [hsym u, aux_swapTwoLinearIsometry_apply]
  constructor
  · intro xi
    let p : ℂ := FourierTransform.fourier (fun u => (Psi u : ℂ))
      (WithLp.toLp 2 ![xi, -xi])
    have hneg : -(WithLp.toLp 2 ![xi, -xi] : EuclideanSpace ℝ (Fin 2)) =
        WithLp.toLp 2 ![-xi, xi] := by
      ext i
      fin_cases i <;> simp
    have hconj : FourierTransform.fourier (fun u => (Psi u : ℂ))
        (WithLp.toLp 2 ![-xi, xi]) = starRingEnd ℂ p := by
      rw [← hneg]
      simpa [p] using aux_fourier_conj_of_real Psi (WithLp.toLp 2 ![xi, -xi])
    have heven : FourierTransform.fourier (fun u => (Psi u : ℂ))
        (WithLp.toLp 2 ![-xi, xi]) = p := by
      simpa [p] using aux_fourier_diagonal_even_of_swap Psi hsym' xi
    have hstar : p = starRingEnd ℂ p := heven.symm.trans hconj
    refine ⟨p.re, ?_⟩
    change p = (p.re : ℂ)
    apply Complex.ext
    · simp
    · have him : p.im = -p.im := by
        simpa using congrArg Complex.im hstar
      simp only [Complex.ofReal_im]
      linarith
  · exact aux_fourier_diagonal_even_of_swap Psi hsym'

end

end Auto
